privacyguides/privacyguides.org

_data/software/browsers/ungoogled-chromium.yml, collections/_evergreen/browsers.html
Under worth mentioning, added ungoogled chromium repo of eloston so newbies can get an official link instead of other forks in Github.
Resolves: #
=> Added Repo Link of Ungoogled Chromium

_includes/legacy/sections/hosting-provider.html
The link was a v2 one, which is now deprecated, I updated it to the v3 one.
=> Update njal.la onion link to v3

_includes/legacy/sections/file-encryption.html
=> Remove Kryptor beta label

_data/software/browsers/tor-browser.yml, _includes/legacy/sections/email-providers.html, _includes/legacy/sections/operating-systems.html, _includes/legacy/sections/search-engines.html, _includes/legacy/sections/self-contained-networks.html, _includes/recommendation-card.html, collections/_evergreen/browsers.html, legacy_pages/software/passwords.html
Searx: https://searx.space
DDG: https://old.reddit.com/r/duckduckgo/comments/oc07wj/news_duckduckgo_search_now_available_via_tor/
Njalla: https://twitter.com/njal_la/status/1371832961381904393
Tor: https://www.torproject.org
Debian: https://onion.debian.org
Resolves #52, Resolves #74, Resolves #80
=> Update V2 onions to V3, plus minor corrections

README.md
=> Fix #104 -- Readme shows amount of stars of the project 3 time

_includes/legacy/sections/android-operating-systems.html
CalyxOS also support one non-pixel phone now, so I added it.
Also, GrapheneOS IS Pixel exclusive again.
=> Calyxos update

_includes/legacy/sections/operating-systems.html
Fixed Ubuntu Typo
> Ubuntu is a Linux distribution developed by Canonical Ltd. Ubuntu is a reliable **and** distribution that is user-friendly and can be run on desktops, servers, and IoT devices.
> Ubuntu is a Linux distribution developed by Canonical Ltd. Ubuntu is a reliable distribution that is user-friendly and can be run on desktops, servers, and IoT devices.
=> Ubuntu Typo

_includes/legacy/sections/vpn.html
Updates the IVPN section with a note that they also accept Monero.
No COI, not currently/ever using IVPN.
=> Add monero note (ivpn)

_data/software/browsers/bromite.yml, legacy_pages/providers.html
Bromite is recommended twice, this deletes one of them.
I also removed a dead hyperlink left over from my previous PR as well.
=> Remove duplicated Bromite

legacy_pages/providers/vpn.html
=> Remove duplicated entry

_includes/legacy/sections/browser-addons.html
=> Remove Etag Stoppa

legacy_pages/providers/vpn.html
I missed this in my previous PR
=> Remove duplicated line

_includes/legacy/sections/android-operating-systems.html
Removed LineageOS - Calyx and Graphene are better alternatives.
=> Remove LineageOS

_includes/legacy/sections/calendar-contacts-sync.html
Resolves: Added a warning badge to Fruux under the Worth Mentioning section as it is a proprietary application.
=> Added a warning to Fruux: proprietary application

_includes/legacy/sections/metadata-removal-tools.html
=> Fix Metadata removal tools heading

_includes/legacy/sections/cloud.html
Fixed missing highlights on the cloud page
=> Fixed missing highlights

_includes/legacy/sections/notebooks.html
Removed Tutrl as they haven't updated their source code in over 8 months.
=> Remove Turtl

collections/_posts/2019-11-09-firefox-privacy.md
[This Reddit post ](https://www.reddit.com/r/PrivacyGuides/comments/qtfrj2/typo/) pointed it out.
There are a lot of outdated stuff on that post. We should remove various sections of it altogether in another PR.
=> Update URLs to privacyguides.org

_includes/legacy/sections/social-news-aggregator.html
=> Remove Aether

_includes/legacy/sections/social-news-aggregator.html
=> Removed Akasha

_includes/legacy/sections/social-news-aggregator.html
I think [join-lemmy.org](join-lemmy.org) is the website of Lemmy. The [old one](dev.lemmy.ml)'s certificate is not valid and [their repositories ](https://github.com/LemmyNet) point to [join-lemmy.org](join-lemmy.org).
=> Update the homepage  of Lemmy

_data/providers/cloud/2_proton-drive.yml
Better explanation for threat modeling with protondrive
=> Better protondrive description

_data/software/video-streaming/1_freetube.yml, _data/software/video-streaming/2_lbry.yml
Changed "if this is in your threat model" to "depending on your threat model" to make it more clear.
=> Better wording for the video page

legacy_pages/providers/social-networks.html
=> Fix broken link, remove outdated link

_data/nav/2_providers.yml
This is now under Video Streaming
=> Delete video platforms nav item

_data/providers/cloud/3_tahoe-lafs.yml
This was a mistake I made during the conversion.
The privacy policies for the new layout got fixed and now I realized my mistake, so yeah xD
=> Remove tahoe-lafs privacy policy

_includes/legacy/sections/file-sync.html, _includes/legacy/sections/teamchat.html, collections/_evergreen/video-streaming.html, legacy_pages/software/real-time-communication.html
Closes: https://github.com/privacyguides/privacyguides.org/issues/129
=> Fix video streaming anchor links

index.html
=> Remove Homepage Banner Notice

collections/_posts/2021-12-01-firefox-privacy-2021-update.md
Fixed some minor typos and wording issues in the new Firefox blog post.
=> Fix some typos and wording in new Firefox blog post

_data/providers/search-engines/2_startpage.yml
Closes https://github.com/privacyguides/privacyguides.org/issues/414
=> Fixed Startpage

_includes/legacy/sections/instant-messenger.html
Resolves: A typo in the [Centralized Real-Time Communications page](https://privacyguides.org/software/real-time-communication/#centralized) for Signal's audits (indepedently -> independently).
=> Fix typo in Real-Time Communication

_data/software/messengers/2_element.yml
Typo fixes in Element.io's card
=> Typo fixes in Element.io's card

collections/_pages/providers/dns.md
=> Fix broken DNS definitions anchor

_data/operating-systems/android/1_grapheneos.yml, _data/providers/cloud/3_tahoe-lafs.yml
Enable dark theme icons for Tahoe and GrapheneOS
=> Dark theme icons

_data/dns/controld.yml
Resolves: Lack of ControlD on the DNS Providers list ;)
Thanks so much for the work on the guide.
=> Adding ControlD to list of DNS providers.

_data/software/messengers/2_element.yml
Updated the notes because this is pretty bad
=> Update element description

collections/_evergreen/android.html
They finally updated to Chromium 97.
=> Removal of the warning on CalyxOS

_includes/legacy/sections/file-sharing.html
Resolves: [#597](https://github.com/privacyguides/privacyguides.org/issues/597)
=> Remove framadrop, no longer exists

_data/providers/cloud/2_proton-drive.yml
Resolves: [#558](https://github.com/privacyguides/privacyguides.org/issues/558)
=> Fix Proton Drive source link

_data/software/video-streaming-front-ends/2_piped.yml
Fixed a typo in Piped.
Resolves: #663 
I fixed a small typo in the Piped section.
=> Fixed Piped typo

_includes/legacy/sections/password-managers.html
The warning badge is useless and doesn't really say anything meaningful.
=> Remove useless warning badge

_includes/legacy/sections/email-providers.html
=> Update Tuanota payment methods description and badge

_includes/legacy/sections/email-providers.html
Particular sounds too vague in my opinion
=> Fixed CTemplar vague description

legacy_pages/providers/email.html
---
Affected pages: https://privacyguides.org/providers/email/#selfhosting
=> Fix position of Mailcow

_data/software/browsers-desktop/1_firefox.yml, _data/software/browsers-mobile/1_bromite.yml, _data/software/browsers-mobile/2_firefox.yml, _data/software/browsers-mobile/3_firefox_focus.yml, _data/software/browsers-resources/1_ublock_origin.yml, _data/software/browsers-resources/2_terms_of_service_didnt_read.yml, _data/software/browsers/1_tor-browser.yml, collections/_evergreen/browsers.md
=> Browser page cleanup

legacy_pages/software/networks.html
It is irrelevant to the site and what's being discussed
=> Remove Dark Diaries

_data/software/browsers-mobile/2_safari.yml
Remove anti-fingerprinting from the description of Safari.
=> Remove anti-fingerprinting

_data/software/browsers-desktop/1_firefox.yml, _data/software/browsers-mobile/2_safari.yml
Add instructions to disable telemetry and reorder items to the same order they appear in settings.
=> Add Disabling of Telemetry to the Firefox Desktop Card

_data/software/browsers-desktop/1_firefox.yml, _data/software/browsers-mobile/1_bromite.yml
Fixed the headers on the Firefox and Bromite cards to be better and more consistent.
=> Browser consistency fix

_data/software/browsers-resources/1_ublock_origin.yml, _data/software/browsers-resources/2_adguard.yml
PR inspired by https://github.com/privacyguides/privacyguides.org/discussions/662#discussioncomment-2375887
Changes:
- Update AdGuard card links
- Recommend to enable AdGuard's *#recommended* filter lists (I would like input on this)
- Add notes about attack surface in regard to filter lists
- Minor grammatical and phrasing updates
=> Update AdGuard & uBlock Origin cards

_data/software/video-streaming-clients/1_freetube.yml
GitHub link links to the Issues tab of the repo. Fixed that.
=> Fix FreeTube GitHub link

_data/software/browsers-resources/1_ublock_origin.yml
Add GitHub repo link in the uBlock Origin card.
=> Add GitHub link in uBlock Origin card

_data/software/browsers-mobile/2_safari.yml
Improved the description for Safari sync to be more accurate and less confusing.
Resolves: #737
=> Safari sync improvement

_data/operating-systems/linux-desktop/3_archlinux.yml
https://www.reddit.com/r/PrivacyGuides/comments/tiq8e9/incorrect_info_on_new_linux_page/
Resolves: #
=> Fix archinstall's release date

_data/software/messengers/1_signal.yml, _data/software/messengers/2_element.yml
Resolves: Minor typos
- Signal: `access to it` -> `access to them`
- Signal: `can be founded` -> `can be found`
- Element: Add comma
=> Fix minor typos in messengers list

collections/_evergreen/linux-desktop.md
Since writing is about Arch Linux and not a package name/URL
=> Put space between "Arch Linux"

_data/software/browsers-desktop/1_firefox.yml
Added that the search suggestion options are only for the US
=> Slight correction to firefox card

README.md, collections/_evergreen/android.md, collections/_evergreen/browsers.md, collections/_evergreen/linux-desktop.md, collections/_evergreen/real-time-communication.md, collections/_evergreen/router.md, collections/_evergreen/threat-modeling.md, collections/_posts/2019-08-22-self-hosting-shadowsocks-vpn-outline.md, collections/_posts/2019-10-05-understanding-vpns.md, collections/_posts/2019-10-30-choosing-a-vpn.md, collections/_posts/2019-11-09-firefox-privacy.md, collections/_posts/2021-09-14-welcome-to-privacy-guides.md, collections/_posts/2021-12-01-firefox-privacy-2021-update.md, notices.md
Various small edits for capitalization, spelling, & consistent style.
There was also 1 sentence that had 1 repeated phrase under the section
"System counting".
=> Small edits in linux-desktop.md

collections/_evergreen/real-time-communication.md
=> Fix link to old blog

_includes/legacy/sections/social-news-aggregator.html
Not sure if I'm allowed to make two changes at once but I felt it would be easier to kill two birds with one stone. I fixed up a grammatical error ("A is a public..."). I also decided to link to the GitLab repo for Postmill, as I never heard of Postmill before and I figured others might not know what it was either.
Resolves: #
=> Small grammar correction and link to Postmill.

docs/real-time-communication.md
Resolves: # 
I fixed so there's a Session logo next to its recommendation on the page instead of Briar's logo
=> Make Session's logo appear next to its recommendation

docs/multi-factor-authentication.md
Affected page: https://privacyguides.org/multi-factor-authentication/#authenticator-apps
=> Move 2FA app download links inline w/ the cards

docs/bounty.md, mkdocs.yml
https://github.com/privacyguides/privacyguides.org/blob/1dc59d4748c1911b7354ef622f38dcee48e033f4/docs/bounty.md
=> Article bounties

mkdocs.yml
Resolves: https://github.com/privacyguides/privacyguides.org/issues/853
=> Fix "get involved" link

docs/blog/2019/11/09/firefox-privacy.md
Closes https://github.com/privacyguides/privacyguides.org/issues/868
=> Warning on Firefox privacy blog post (#868)

docs/vpn.md
I added http://doineedavpn.com/ to the Sources and Further Reading section. It is a quiz by IVPN where the user chooses the issues they want to solve and benefits they look for in their VPN, and informs them whether or not a VPN would actually address any of these issues. 
I think that this website would be a great addition to the Further Reading section because it challenges the misconceptions surrounding VPNs, especially with the aggressive marketing from VPN companies, and helps users decide whether or not they actually need a VPN. It also tells the user if Tor would be a better solution for them. It certainly helped me when I was looking into getting a VPN!
I know that Privacy Guides already addresses these misconceptions, but I still think it's a fantastic source, especially if you …
=> Add doineedavpn.com to Sources and Further Reading

docs/metadata-removal-tools.md
ExifCleaner's privacy policy was incorrectly linked to Bitwarden's.
=> Remove ExifCleaner privacy policy

docs/passwords.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/879
=> Fix KeepassDX F-Droid link

docs/browsers.md, docs/calendar-contacts.md, docs/cloud.md, docs/email-clients.md, docs/encryption.md, docs/file-sharing.md, docs/metadata-removal-tools.md, docs/notebooks.md, docs/passwords.md, docs/productivity.md, docs/real-time-communication.md, docs/self-contained-networks.md, docs/video-streaming.md
- Use Mac App Store title and icon for MAS apps
- Reorder some download icons for site-wide consistency
- Update Session F-Droid link to use F-Droid icon
=> Minor download icon updates

docs/multi-factor-authentication.md
- Add privacy policies for Aegis and Raivo OTP
- Mention Raivo OTP Mac app
- Mention Raivo OTP iCloud syncing functionality
- Add Mac App Store link for Raivo OTP
=> Update authenticator apps section

docs/social-networks.md
Pleroma download link is not labeled consistently.
=> Fix unlabeled download link

docs/calendar-contacts.md, docs/tools.md, mkdocs.yml, theme/overrides/blog.html, theme/overrides/home.html
Lists all recommended tools on privacyguides.org/tools, example:
=> Single-page recommendations

docs/tools.md, theme/overrides/home.css, theme/overrides/home.html
Closes #899, Closes #901
On hover:
=> Fix homepage button

docs/index.md, theme/overrides/home.html
=> Remove homepage footer

docs/tools.md
Use correct stylizing of the following software projects:
* KeePassXC
* KeePassDX
* OnionShare
* ExifTool: https://exiftool.org/
* Vaultwarden: https://github.com/dani-garcia/vaultwarden/wiki
* NewPipe (in picture alt text - visible text on site is ok)
=> Use correct stylization of software project names

docs/passwords.md
Fixes https://github.com/privacyguides/privacyguides.org/commit/8ef8e2a263b4e6fd145eb2c171d407de8591e3b3#commitcomment-70678679
=> Fix broken link

docs/technology/dns.md
I updated the "Should I use encrypted DNS" section because I felt it wasn't very clear.
The flow chart is better suited here, I polished it up a bit and added a new choice. I think security and performance of 3rd party DNS should be mentioned since the table on the recommandation also talks about filters.
=> Encrypted DNS: Should I use encrypted DNS update 

docs/about/notices.md, docs/javascripts/LICENSE.mathjax.txt
While I was there, I also removed obsolete HTML.
=> Update outdated licenses in Notices

docs/about/privacy-policy.md
Closes: https://github.com/privacyguides/privacyguides.org/pull/943
Closes: https://github.com/privacyguides/privacyguides.org/issues/942
=> Update broken links on privacy policy

docs/email-clients.md
It was incorrectly linked to K-9 mail's F-Droid link.
=> Fix FairEmail F-Droid download link

docs/vpn.md
Added a helpful link to VPN criteria.
=> Add link to VPN criteria

docs/tools.md
* Lowcaps according to its [homepage](https://mailcow.email/)
=> Use styilization of mailcow

docs/android.md
I reordered some things that were said about F-Droid, and made Droid-ify a subheading.
I think this fixes https://github.com/privacyguides/privacyguides.org/pull/720#issuecomment-1092820636
=> De-indent "Where to get your applications"

docs/dns.en.md
Changes the macos dns settings instructions. Before the change, it looked like a single settings path, not like two separate ones.
This PR also rewords a sentence to be more correct
=> Clarify macOS DNS instructions and reword a sentence

docs/security/multi-factor-authentication.en.md
Correct spelling of "separate" and "document"
=> Correct 2 typos on MFA page

docs/dns.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1007
=> Link to ECS

docs/linux-desktop.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1023
=> Mention OpenQA

docs/linux-desktop.en.md
=> Removed OBS as it is not involved with testing

docs/metadata-removal-tools.en.md, docs/setup/integrating-metadata-removal.en.md
Resolves: https://github.com/privacyguides/privacyguides.org/issues/1005
=> Reduce number of EXIF links

docs/news-aggregators.en.md
=> Correct spelling of YouTube

docs/search-engines.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1042
=> searx.me link fix

docs/tools.en.md
- Change 'recommended' link to the DNS table (previous link had a non-existent anchor)
- Rephrase suggestion snippet because of #1001
- Separate the 'Learn More' link from the paragraph
=> Update DNS section on tools overview page

docs/email-clients.en.md
=> fix a typo on the email clients page

docs/video-streaming.en.md
Fixes minor capitalization error
=> Fix capitalization of FreeTube

docs/technology/dns.en.md
replacing Wireguard with Wireshark
and fixes minor capitalization error
=> Wireshark not Wireguard, and typo

docs/video-streaming.en.md
=> Move "NewPipe x SponsorBlock" to NewPipe sub-section

docs/android/overview.en.md, docs/android/security.en.md, includes/abbreviations.en.md, mkdocs.yml
Recommend a custom OS on the Android overview page and link to our OS recommendations.
=> Recommend a custom Android OS

docs/linux-desktop.en.md, docs/security/multi-factor-authentication.en.md, docs/setup/integrating-metadata-removal.en.md
Use "set up" as a verb, instead of "setup" as a noun
=> Use "set up", instead of "setup"

docs/android.en.md, docs/browsers.en.md, docs/calendar-contacts.en.md, docs/cloud.en.md, docs/dns.en.md, docs/email-clients.en.md, docs/encryption.en.md, docs/file-sharing.en.md, docs/metadata-removal-tools.en.md, docs/multi-factor-authentication.en.md, docs/news-aggregators.en.md, docs/notebooks.en.md, docs/passwords.en.md, docs/productivity.en.md, docs/qubes.en.md, docs/real-time-communication.en.md, docs/router.en.md, docs/search-engines.en.md, docs/self-contained-networks.en.md, docs/stylesheets/extra.css, docs/video-streaming.en.md
see https://github.com/privacyguides/privacyguides.org/discussions/1076#discussioncomment-2618351
=> Use dropdown for download links

docs/video-streaming.en.md
changes: https://github.com/privacyguides/privacyguides.org/pull/1077/files#diff-8adec93397671c861254b923908e7a16e1cd9091e44a8f2c73b80140d806fd3e
=> Minor video streaming phrasing updates

docs/passwords.en.md
I thought this was fixed at #920.
=> Fix capitalization of KeePassXC and KeePassDX

docs/android.en.md, docs/android/overview.en.md, docs/browsers.en.md, docs/video-streaming.en.md
For visual consistency without relying on people having good fonts installed.
=> Replace emojis with icons

docs/android.en.md, docs/browsers.en.md, docs/cloud.en.md, docs/email-clients.en.md, docs/metadata-removal-tools.en.md, docs/multi-factor-authentication.en.md, docs/news-aggregators.en.md, docs/notebooks.en.md, docs/productivity.en.md, docs/real-time-communication.en.md, docs/video-streaming.en.md
PR started off with productivity tool JS warning consistency changes, but dng added some more updates
=> General site-wide consistency updates

docs/linux-desktop/hardening.en.md, docs/linux-desktop/overview.en.md, docs/linux-desktop/sandboxing.en.md, docs/passwords.en.md, includes/abbreviations.en.md
Also included abbreviations plugin in the Linux knowledge base pages.
=> Add more abbreviations

docs/android.en.md, docs/browsers.en.md, docs/calendar-contacts.en.md, docs/cloud.en.md, docs/dns.en.md, docs/email-clients.en.md, docs/email.en.md, docs/encryption.en.md, docs/file-sharing.en.md, docs/linux-desktop.en.md, docs/metadata-removal-tools.en.md, docs/multi-factor-authentication.en.md, docs/news-aggregators.en.md, docs/notebooks.en.md, docs/passwords.en.md, docs/productivity.en.md, docs/qubes.en.md, docs/real-time-communication.en.md, docs/router.en.md, docs/search-engines.en.md, docs/self-contained-networks.en.md, docs/video-streaming.en.md, docs/vpn.en.md
Resolves: #1094 
Preview: https://github.com/privacyguides/privacyguides.org/pull/1095#issuecomment-1107909848
=> Update primary button text

docs/search-engines.en.md, includes/abbreviations.en.md
- Also added PII to abbreviations
=> Update SearXNG wording and mention it is a fork

docs/about/privacy-policy.en.md, mkdocs.yml, theme/partials/integrations/analytics/plausible.html
Waiting to merge this until #1111 is discussed and decided.
=> Plausible analytics

docs/real-time-communication.en.md
=> Update Session description phrasing to not use "users"

docs/about/donate.en.md
- Capitalization of certain services
- Fix Jonah's mailto link
=> Fixes to donation about page

docs/browsers.en.md
=> Update Firefox for Android description

docs/file-sharing.en.md
=> Update Syncthing download links

docs/technology/dns.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1144
=> Fix what typo in DNS

docs/dns.en.md
=> Add download links to dnscrypt-proxy

docs/self-contained-networks.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1154
=> Correct i2p android link

docs/email.en.md, mkdocs.yml
as discussed in #1123 
Closes: https://github.com/privacyguides/privacyguides.org/issues/1138
to do:
- why, when, advantages, disadvantages, etc
=> Update email aliasing section

docs/vpn.en.md
https://www.reddit.com/r/PrivacyGuides/comments/ugwghr/monero_is_now_supported_by_mullvad/
=> Mullvad now accepts Monero

docs/productivity.en.md
Closes https://github.com/privacyguides/privacyguides.org/issues/1164
=> Fix OnlyOffice Linux link

Pipfile.lock, docs/about/donate.en.md, docs/index.en.md, mkdocs.yml, theme/overrides/home.en.html
Do we have an issue with adding this? https://privacyguides-privacyguides-org-preview-pr-1152.surge.sh/about/donate/#backers
=> Show backers on donation page

docs/calendar-contacts.en.md
These two recommendations felt a little barren before, especially Tutanota.
=> Add more detail to Proton Calendar & Tutanota Calendar

docs/vpn.en.md
This has been bothering me for a while ever since I originally worded it lol https://github.com/privacyguides/privacyguides.org/pull/859#discussion_r841133696
=> Minor wording update to "Do I Need A VPN?"

docs/email.en.md
minor update to #1133
- Referenced the *+ email aliasing trick* as "plus addressing" instead (#L235)
- Added note about email aliasing in case your email provider ceases operation (#L237)
- Changed "Free features" to "Notable free features" to clarify the features listed aren't all the potential available free features (#L276 & #L302)
=> Minor updates to email aliasing section (re: #1133)

docs/notebooks.en.md
=> Add Joplin privacy policy

docs/email.en.md
Tutanota removed their plans for a .onion address in their roadmap.
=> Minor updates to email page

docs/notebooks.en.md
closes https://github.com/privacyguides/privacyguides.org/issues/1185
=> Fix link in notebooks.en.md

docs/email.en.md
=> Missing link

docs/file-sharing.en.md
The original description isn't helpful, it's like an advertisement.
=> Update Syncthing description

docs/file-sharing.en.md
Fixed a grammar issue in the FreedomBox card
=> Grammar fix in FreedomBox card

docs/security/multi-factor-authentication.en.md
Resolves: # 
Changed "receive from an SMS or app." to "receive from SMS or an app." as **S**MS starts with an vowel but **a***pp* is. Basically minor a grammar change in a nutshell.
=> Minor grammar fix in the first paragraph in Multi-factor Authentication

docs/cloud.en.md
E2EE eliminates trust in your provider, so I updated the description to reflect that.
=> Fix wording in cloud storage page

docs/cloud.en.md, docs/email-clients.en.md, docs/email.en.md, docs/qubes.en.md, docs/router.en.md, docs/search-engines.en.md, docs/self-contained-networks.en.md
The title and subtitle are redundant here. Also the blurb about browsing the "dark net" is unnecessary as the title is self-explanatory.
=> Make headings consistent and remove redundant descriptions

docs/browsers.en.md
Resolves: # 
Made the extended sentence for ToS;DR more smoothy and less choppy by using transition words.
=> Made the "Extended Description" for ToS;DR go more smoothy.

docs/file-sharing.en.md
=> Magic Wormhole consistency fix

docs/security/multi-factor-authentication.en.md
Fixed a typo in the MFA guide.
=> Fix typo in MFA guide

docs/technology/dns.en.md
Updated the DNSSEC description to make it more thorough yet easier to understand.
=> Update "What is DNSSEC?"

docs/android.en.md, docs/metadata-removal-tools.en.md, docs/multi-factor-authentication.en.md
You wrote "warning" on other Warning Boxes AFAIK, I think it would be better to stick to it.
It's confusing to have too many terms to explain a danger IMO
=> Change "Attention" to "Warning" in Warning Box Message

docs/basics/account-deletion.en.md
Fix some grammar/wording things on the account deletion article.
=> Grammar and wording fixes

docs/android.en.md, docs/multi-factor-authentication.en.md, docs/notebooks.en.md
Closes https://github.com/privacyguides/privacyguides.org/issues/1235
=> Fix source consistency

docs/cloud.en.md
With this change, I mainly wanted to link to the encryption software page.
I had some difficulties finding a good way to phrase it, so any suggestions are welcomed!
=> Update cloud storage intro description

docs/browsers.en.md
- Revamped the layout of the Brave Browser section
- General updates to browser page
=> Improvements to the browser page (especially the Brave section)

docs/browsers.en.md
"Additional filter lists can impact performance may increase attack surface." Missing "and"
=> grammar fix to filter list sentence 

docs/vpn.en.md
- Corrected the number of available countries for Mullvad and ProtonVPN
- Put the last updated note in annotation format
=> Update VPN providers' # of countries

docs/browsers.en.md
=> Change Warning to Danger for Tor Browser Warning Box

docs/search-engines.en.md
https://github.com/privacyguides/privacyguides.org/issues/1264
=> Fix spelling mistake in search engines

docs/tools.en.md
=> Change MullvadDNS to Mullvad in Overview page

docs/stylesheets/extra.css, mkdocs.yml
=> Change the light switch (sun/moon)

docs/stylesheets/extra.css
Colors on new page do not meet accessibility standards.
=> Meet accessibility standards with text colors

docs/browsers.en.md
Couple things:
- Split up the paragraph to make it easier to read
- Improve the overall sentence flow
- Mention that the Tor Browser is designed to prevent fingerprinting
- Put a slightly greater emphasis on not changing the browser settings (beyond the security levels)
=> Improve Tor Browser description

docs/browsers.en.md
Changing wording following Writing Style https://github.com/privacyguides/privacyguides.org/wiki/Writing-Style#address-people-directly
=> Changing wording Tor Browser

docs/basics/erasing-data.md, docs/browsers.en.md, docs/email.en.md, docs/search-engines.en.md, docs/vpn.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1326
Closes: https://github.com/privacyguides/privacyguides.org/issues/1323
Closes: https://github.com/privacyguides/privacyguides.org/issues/1324
=> Minor fixes to various pages

docs/vpn.en.md
Proton updated the pricing of their VPN. I updated the description to fit these changes.
Source: [https://protonvpn.com/pricing/](https://protonvpn.com/pricing/)
=> Correct Proton VPN pricing

docs/email.en.md
=> Correct Proton Mail zero-access encryption information

docs/android/grapheneos-vs-calyxos.en.md, docs/basics/account-deletion.en.md, docs/basics/email-security.en.md, docs/basics/vpn-overview.en.md, docs/email-clients.en.md, docs/email.en.md, docs/vpn.en.md, mkdocs.yml
=> Separate articles and recommendations

docs/basics/erasing-data.md
=> Data Erasure Grammar Fixes

docs/linux-desktop/hardening.en.md
=> Fix links in linux hardening guide

docs/basics/vpn-overview.en.md
=> Fix typos on VPN services page

docs/android.en.md, docs/android/grapheneos-vs-calyxos.en.md
=> Update microG on Calyx information

theme/main.html, theme/overrides/blog.en.html, theme/overrides/home.en.html
=> Preload header font

docs/android.en.md, docs/assets/stylesheets/extra.css, docs/browsers.en.md, docs/calendar-contacts.en.md, docs/cloud.en.md, docs/dns.en.md, docs/email-clients.en.md, docs/email.en.md, docs/encryption.en.md, docs/file-sharing.en.md, docs/metadata-removal-tools.en.md, docs/multi-factor-authentication.en.md, docs/news-aggregators.en.md, docs/notebooks.en.md, docs/passwords.en.md, docs/productivity.en.md, docs/real-time-communication.en.md, docs/self-contained-networks.en.md, docs/video-streaming.en.md
Superseeds: #1349
Updated download links
Resolves: # 
- Added text to all download links
- Now uses grid layout
- Removed `{.card-link}` from all download links
=> Add grid layout for download links

docs/basics/vpn-overview.en.md, docs/vpn.en.md
Long overdue cleanup, this will require https://github.com/privacyguides/privacyguides.org/pull/1219 and https://github.com/privacyguides/privacyguides.org/pull/1310  and https://github.com/privacyguides/privacyguides.org/pull/1173 to be merged.
@jonaharagon I'm thinking we might want to republish our "trouble with VPN review sites" article as well.
I'm thinking we should remove some of the dated VPN breaches, those are all from 1+ years ago.
I'm thinking some of the other links at the bottom would be better placed within the text.
=> VPN/Email clean-up

docs/basics/tor-overview.md
The 2 videos are from Computerphile. He explains well about the tor network and hidden services, I think we could add it IMO
=> Add 2 video links for Tor Overview in further reading

docs/vpn.en.md
Currently, a nested list doesn't appear as such, making it confusing to read
Fixed by adding a few spaces
=> Fix nested list on VPN page

docs/vpn.en.md
This PR fixes some punctuation issues concerning the use of "e.g." and "etc"
=> Fix punctuation on VPN page

docs/email.en.md
https://proton.me/support/payment-options
=> Add Cash option in Protonmail payments

docs/basics/tor-overview.md
=> Clarify which security settings we talk about

docs/search-engines.en.md
=> Move Brave Search to top of Search Engines page

docs/android.en.md
https://divestos.org/index.php?page=devices&base=LineageOS#device-lemonadep
=> Update OnePlus supported devices for DivestOS

docs/browsers.en.md
=> Minor fix to AdGuard for iOS

docs/calendar-contacts.en.md
This concerns the introductory sentence which reads -
> Calendaring and contacts are some of the most sensitive data possess.
=> Fix for a minor grammatical issue in Calendars section.

docs/tools.en.md
=> Proton Calendar on Tools page, correction

docs/email-clients.en.md
Added a note k-9 will be the future thunderbird android client
=> K-9 and Thunderbird

docs/linux-desktop/hardening.en.md
Resolves: N/A
Under the Linux hardening page, I deleted an extra "for" that precedes another "for" that shouldn't be there. For what? Yes.
=> Fix minor typo Linux page

docs/email.en.md
Fixed a typo
Resolves: minor eye pain
=> Fix minor typo in Simple Login description

docs/productivity.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1462
=> Move Cryptpad to office suite

docs/tools.en.md
- Changing introduction
- Added bitwarden-send
- Reorder DivestOS and CalyxOS
- Reorder Brave and DDG
- Rename **Encryption Tools** to **Encryption Software** (as it is written like that in the left)
**Again, don't mind the multiple commits, I messed with my branches**
=> Tools Page reorder and fix

docs/index.en.md
Not **Everyone** has something to hide. I don't think hiding is the right term here.
It is about protecting an inherent right
=> Fix grammar, punctuation and wording on Home page

docs/vpn.en.md
https://www.ivpn.net/blog/ivpn-apps-security-audit-2022-concluded/
=> Add 2022 IVPN audit

docs/vpn.en.md
https://protonvpn.com/blog/no-logs-audit/
=> Add Proton VPN no-logs audit

docs/vpn.en.md
Feel free to edit my text as usual
=> Add June 2022 audit Mullvad

docs/android.en.md, docs/browsers.en.md, docs/calendar-contacts.en.md, docs/cloud.en.md, docs/dns.en.md, docs/email-clients.en.md, docs/email.en.md, docs/encryption.en.md, docs/file-sharing.en.md, docs/linux-desktop.en.md, docs/metadata-removal-tools.en.md, docs/multi-factor-authentication.en.md, docs/notebooks.en.md, docs/passwords.en.md, docs/productivity.en.md, docs/real-time-communication.en.md, docs/router.en.md, docs/search-engines.en.md, docs/video-streaming.en.md, docs/vpn.en.md
- **"third party"** change to **"third-party"**, same goes for open-source and closed-source
Every rules of grammar/punctuation have been check (by me) for every grammar/punctuation I fixed. So if you have a doubt, just ask me why I did it as I did it for a reason. That said, I probably did mistakes.
=> Fix grammar, punctuation, duplications in Recommendations

docs/advanced/erasing-data.md, docs/advanced/integrating-metadata-removal.en.md, docs/android/grapheneos-vs-calyxos.en.md, docs/android/overview.en.md, docs/basics/account-deletion.en.md, docs/basics/common-threats.en.md, docs/basics/dns-overview.en.md, docs/basics/email-security.en.md, docs/basics/multi-factor-authentication.en.md, docs/basics/threat-modeling.en.md, docs/basics/tor-overview.md, docs/basics/vpn-overview.en.md, docs/linux-desktop/hardening.en.md, docs/linux-desktop/overview.en.md, docs/linux-desktop/sandboxing.en.md
As English is not my main language, I probably did some mistakes.
_Note :_
- "third party" changed to "third-party" same goes for open-source and closed-source
Every rules of grammar/punctuation have been check (by me) for every grammar/punctuation I fixed. So if you have a doubt, just ask me why I did it as I did it for a reason. That said, I probably did mistakes.
=> Fix grammar, punctuation, duplications in Knowledge Base

docs/advanced/integrating-metadata-removal.en.md
Just stick to warning instead of attention, to keep consistency on the website
=> Change "attention" to "warning" in Metadata Removal Guide

docs/browsers.en.md
=> Add language resistance brave

docs/linux-desktop.en.md, docs/linux-desktop/hardening.en.md, docs/linux-desktop/overview.en.md, includes/abbreviations.en.md
- Rewrite the Secure Boot section
- Add sysfs access restriction
- Add SUID permission hardener
- Add secure timesync
- Update info about LKRG
- Elaborate a bit more on Tails
=> Update Linux pages

docs/browsers.en.md, docs/tools.en.md
This PR adds Brave as a recommendation for Android
=> Add Brave Android in Mobile browser recommendations

docs/basics/vpn-overview.en.md, docs/linux-desktop/hardening.en.md
- tracker : #1532 
- I added a missing ”
=> Fix couple typos VPN & Linux desktop hardening pages

docs/android.en.md, docs/android/grapheneos-vs-calyxos.en.md
=> Rephrase GrapheneOS vs CalyxOS page

docs/basics/multi-factor-authentication.en.md
In accordance to #1473
I forgot to change mutlifactor to multi-factor (same for multi-function)
=> Changed multifactor to multi-factor

docs/linux-desktop.en.md
=> Rephrase Tails recommendation

docs/basics/common-threats.en.md
Chrome OS rebranded to ChromeOS
https://www.theverge.com/tldr/2022/7/14/23219443/google-chromeos-not-chrome-os-branding
I grep every files, this is the only one
=> Update Chrome OS to ChromeOS

docs/email.en.md
AnonAddy plan was mentioned as $12/month instead of $12/year.
Resolves: #
=> Fix typo of pricing for Anonaddy

docs/browsers.en.md
=> Add link to gorhill's blocking modes

docs/desktop-browsers.en.md, docs/mobile-browsers.en.md, docs/tools.en.md, mkdocs.yml
Resolves: #1228 
Changed the browser page into a mobile and desktop page for better organization/less confusion.
=> Add separate desktop and mobile browser pages

docs/cloud.en.md
=> Add Proton Drive platforms

docs/tools.en.md
=> Split browsers in the tools page

docs/mobile-browsers.en.md, docs/tools.en.md
=> Add Tor Browser to mobile browsers (Android)

docs/tools.en.md
=> Fix broken mobile browsers hyperlinks

docs/vpn.en.md
Resolves: #1613
Proton VPN expanded to 64 countries so I also corrected that.
=> Proton VPN 2FA and countries correction

.github/workflows/pages.yml, .github/workflows/preview.yml, README.md, mkdocs.production.yml, mkdocs.yml
=> Split mkdocs configuration file

docs/encryption.en.md
=> Fix typo in Tomb section

docs/desktop-browsers.en.md
Resolves: https://github.com/privacyguides/privacyguides.org/issues/1652
=> Remove AdGuard mention in Desktop Browsers page

docs/android.en.md
=> Fix Neo Store listing

mkdocs.yml
Disabled GitHub's "Organization Discussions" feature which has completely broken notifications and GitHub mobile app integration.
=> Update discussions link

docs/video-streaming.en.md
Resolves: https://github.com/privacyguides/privacyguides.org/issues/1668
=> Remove NewPipe X SponsorBlock

docs/encryption.en.md
=> Fix Bitlocker for Home edition guide

.github/workflows/pages.yml, .github/workflows/preview.yml, Pipfile, Pipfile.lock, README.md, mkdocs.production.yml, mkdocs.yml
https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
=> Enable social cards

docs/passwords.en.md, docs/tools.en.md
Since #1666 wasn't reviewed by anyone after the latest changes to the PR 😜
=> Password manager corrections

docs/passwords.en.md
=> Grammar fixes on the 1Password card

Pipfile, Pipfile.lock, README.md, data/articles.yml, docs/articles.en.md, docs/news-aggregators.en.md, mkdocs.production.yml, mkdocs.yml
Discussion: https://github.com/privacyguides/team/discussions/25
=> Blog replacement

.github/CODEOWNERS, docs/CODE_OF_CONDUCT.md, docs/coc.md, mkdocs.yml
=> Add Code of Conduct to website

README.md
=> Readme.md aesthetics

docs/passwords.en.md, docs/tools.en.md
=> Add Strongbox to Tools Page

Pipfile, Pipfile.lock, mkdocs.production.yml
Closes: https://github.com/privacyguides/team/issues/30
@mfwmyfacewhen plz confirm this fixes Safari issues :)
=> Disable HTML Minification

docs/android.en.md, docs/assets/stylesheets/extra.css
Adds a brief introduction to Android in general on the Android page, and links to AOSP's homepage & source code.
=> Improve Android introduction

docs/linux-desktop.en.md
=> Update Tails description

docs/android/grapheneos-vs-calyxos.en.md
=> Change GrapheneOS/CalyxOS comparison page name

docs/basics/passwords-overview.en.md
Links to the diceware section were incorrect and led nowhere.
=> Fix Diceware Links

docs/multi-factor-authentication.en.md
=> Fixed iOS capitalization

docs/about/privacytools.en.md, mkdocs.yml
I think you will find this is an extremely generous version of events, because I don't want to create drama. However, due to recent (unethical) events on the development of their website, and his continued personal harassment against me specifically, and against Privacy Guides as a whole, it was long overdue for us to have a central, official resource to point to for future reference.
=> PrivacyTools FAQ

docs/notebooks.en.md
=> Notebooks Page Cleanup

.github/ISSUE_TEMPLATE/config.yml, README.md, docs/android.en.md, docs/articles.en.md, docs/blog/2021/09/14/welcome-to-privacy-guides.md, docs/blog/2021/11/01/virtual-insanity.md, docs/blog/2021/12/01/firefox-privacy-2021-update.md, docs/blog/2022/04/04/move-fast-and-break-things.md, docs/blog/2022/06/09/hide-nothing.md, mkdocs.production.yml, mkdocs.yml
=> Link to forum

docs/basics/threat-modeling.en.md
Edit: Please ignore my messy commit history (unless it unknowingly affects my pull request)!
**Summary**
6 "et cetera" --> "etc.", as per [APA style](https://apastyle.apa.org/style-grammar-guidelines/abbreviations/latin).
6 Missing comma: subordinate clause.
8 Missing comma: embedded clause.
10 Missing comma: subordinate clause.
12 "security/privacy" --> "security and privacy", as per [APA Style](https://apastyle.apa.org/learn/faqs/use-slash-mark).
12 "potential" is redundant here: "could" expresses modality.
14 Simplified sentence structure: conciseness.
16 Updated to title case.
18 "want to" --> "should", as per [style guide](https://github.com/privacyguides/privacyguides.org/wiki/Writing-Style#use-must-for-requirements).
18 Are "those who might want to get ahold of your assets" not …
=> Writing review of threat-modeling.en.md

docs/index.en.md
**Summary**
15 viz. If "Privacy is a human right, inherent to all of us…", then there was no time we *didn't* possess it.
15 Updated tense agreement.
15 Added missing commas for the embedded clause.
15 Added parentheses (an em dash was preferable, but wouldn't render). 
25 Added missing period (to be consistent with the punctuation in the previous H4 (13)). 
17 Added missing commas for the embedded clause.
17 Replaced "counter" with "mitigate", since it's more specific. 
46 Standardized capitalization (given 42-45)
47 Standardized capitalization (given 42-45).
=> Writing review of index.en.md

docs/index.en.md, mkdocs.yml
=> Replaced Reddit with Forum link

docs/basics/vpn-overview.en.md
We should probably make it a little clearer when *not* to use a VPN, such as when using your **[known identity](https://www.privacyguides.org/basics/common-threats/#common-misconceptions)**.
This came up in https://discuss.privacyguides.org/t/is-it-okay-to-use-a-vpn-while-submitting-forms-that-require-personal-information/103/
=> Clarifications, VPN overview

docs/email.en.md
This PR removes the mention of a specific price for Proton Mail, as we've recently opted to remove specific pricing from the website to make things easier to maintain.
=> Remove pricing from Proton Mail card

docs/basics/common-threats.en.md
**Notes**
Need citation:
> The best example of this is trusting data to Google who, given their scale, have had few security incidents by employing industry-leading security experts to secure their infrastructure.
> Generally, mobile operating systems have better application sandboxing than desktop operating systems: Apps cannot obtain root access, and require permission for access to system resources.
> Linux tends to not submit information to system vendors, but it has poor protection against exploits and malicious apps.
> Governments often justify mass surveillance programs as necessary means to combat terrorism and prevent crime.
> However it is most often used to disproportionately target minorities, political dissidents, and many other groups to create a chilling effect on free …
=> Writing review of common-threats.en.md

docs/android/grapheneos-vs-calyxos.en.md
This PR adds our other Android pages as links in the GrapheneOS vs CalyxOS page to increase discoverability.
=> Add links to GrapheneOS vs CalyxOS page

docs/basics/common-misconceptions.en.md, docs/basics/common-threats.en.md, docs/basics/dns-overview.en.md, docs/basics/multi-factor-authentication.en.md, docs/basics/passwords-overview.en.md, includes/abbreviations.en.md, mkdocs.yml
=> KB Cleanup

docs/ios/configuration.en.md, mkdocs.yml
=> Add iOS Guide

netlify.toml
Data from Google Search Console.
=> Redirect past links to current pages

mkdocs.yml
This was broken in #1865. Fixes #1868, thanks @ndygo for the heads up!
=> Fix CoC Page

docs/about/privacy-policy.en.md, docs/about/statistics.md, mkdocs.yml
=> Statistics page

docs/vpn.en.md
=> Remove F-Droid Mentions From vpn.md

docs/email.en.md
https://discuss.privacyguides.org/t/relaxing-email-tls-requirements-on-smtp-port-25/1938/6?u=jonah
=> Clarify email criteria

README.md, docs/about/index.md, docs/index.en.md, mkdocs.yml
=> Update Mastodon Instance Links

docs/vpn.en.md
=> Update IVPN download links

docs/tor.en.md
Removed HTTPS mention from tor.en.md  as per #1884 
Resolves: #1883
=> Removed HTTPS mention from Tor Page

docs/about/index.md
Updating team member info - not 'upating' as per my commit lol
=> Update Team Member Info

docs/about/index.md, mkdocs.yml
=> Add changelog to navbar

README.md
=> Added link to About section

docs/vpn.en.md
Resolves: https://github.com/privacyguides/privacyguides.org/issues/1769
=> Add warning about Proton VPN killswitch Intel Macs

docs/email-clients.en.md
This came up in discussion https://discuss.privacyguides.net/t/hardening-thunderbird/10055
=> Expand Thunderbird description

docs/about/index.md
=> Fix Olivia's Mastodon Link

docs/android.en.md
Link has been replaced https://mastoid.dev/@wonderfall/109484347296835659
=> Replace F-Droid link

.github/ISSUE_TEMPLATE/config.yml
=> Fix broken link on suggestions page

docs/tools.en.md
Added SimpleX Chat to the tools page.
=> Add SimpleX Chat to tools page

docs/encryption.en.md
macOS doesn't prompt you to turn on FileVault during install so I removed that line. Also added reference to the new Advanced Data Protection.
=> Update Filevault for Advanced Data Protection

docs/email.en.md
=> Update Tutanota 2FA to Include Android and iOS

mkdocs.yml
I think we're safe to do so at this point.
=> Remove Twitter icon from footer

docs/encryption.en.md
Advanced Data Protection doesn't actually affect FileVault.
=> Remove Advanced Data Protection from Filevault

docs/email.en.md
=> Add Digital Legacy and Account Termination info to Email Providers

docs/basics/vpn-overview.en.md
=> Updating blog post link

docs/dns.en.md
=> Update Android text to Reflect that Andorid 13 is out

docs/email.en.md, includes/abbreviations.en.md
=> Elaborate on digital legacy PR

docs/productivity.en.md
=> Add Flatpak link for OnlyOffice

docs/cloud.en.md
=> Add iOS download to Proton Drive

docs/passwords.en.md
=> Remove redundant/broken links from Psono description

docs/passwords.en.md
=> Add note on built-in password managers

docs/dns.en.md
=> Remove macOS/iOS config profile info

docs/email.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1932
=> Mention disabling crash reports

docs/dns.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1898
=> Prefer Anycast or Geosteering support

docs/vpn.en.md
=> Update mullvad countries

docs/desktop-browsers.en.md, docs/mobile-browsers.en.md
I noticed they moved a few things around, so this PR fixes that.
=> Updates to Brave description

docs/basics/common-threats.en.md
Added a mention of the Atlas of Surveillance to the Mass Surveillance section, since that might be a useful/interesting resource for some people.
=> Mention "Atlas of Surveillance" in the "Mass Surveillance" section

docs/data-redaction.en.md
=> Add Accrescent download link for ExifEraser

docs/real-time-communication.en.md
=> Adds Windows & Linux download for briar desktop

docs/real-time-communication.en.md
Briar is also cross platform, it just doesn't support macOS and iOS. I think this makes the page look a little cleaner.
=> Remove "Other Messengers" and "Cross Platform Messengers"

docs/android.en.md, docs/cloud.en.md, docs/desktop.en.md, docs/multi-factor-authentication.en.md, docs/productivity.en.md, docs/tor.en.md
There are multiple broken links that I would like to clean up.
=> Fix broken links across the site

docs/basics/account-creation.en.md, docs/vpn.en.md
This PR will include the reported issues from Crowdlin
=> Reported issues from Crowdlin

docs/os/qubes-overview.en.md
=> fix typo in qubes OS overview

.github/dependabot.yml
=> Disable Dependabot for Python dependencies

docs/tools.en.md
=> Fix Briar id in Privacy Tools page

docs/basics/common-threats.en.md, docs/desktop-browsers.en.md, docs/dns.en.md, docs/email-clients.en.md, docs/email.en.md, docs/encryption.en.md, docs/vpn.en.md
At some point, probably the last mkdocs-material update, some admonition keywords were removed: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
=> Fix admonitions

docs/android.en.md, docs/email.en.md
=> Fix typos in Android and Email Services

docs/email.en.md
"Tutanota planning to support AutoCrypt" doesn't even make sense if they're not PGP-based, where did we get this information? Also: https://github.com/tutao/tutanota/issues/198#issuecomment-614597897
=> Remove incorrect information about Tutanota

docs/productivity.en.md
This is plainly ridiculous to me. Even from a security perspective, MDAG is not a standard Office feature, and the default configuration of Office leaves users far more vulnerable to attacks. **Information about using MDAG with Microsoft Office belongs in a Windows guide/tutorial, not a one-line suggestion on this page.** I'm not saying it's not noteworthy, I'm saying this is not the proper place.
This change was originally added in #1423 which describes the PR as "Removes Framadate" and the only discussion of Microsoft Office's MDAG functionality was a single comment in a discussion titled "Remove write.as" - clearly this was not properly discussed in the first place.
=> Remove Microsoft Office suggestion

docs/advanced/dns-overview.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1983
=> Correct dead link in DoH description

docs/desktop-browsers.en.md
Closes: https://github.com/privacyguides/privacyguides.org/discussions/979
=> Disable Firefox Accounts telemetry

docs/os/linux-overview.en.md
https://discuss.privacyguides.net/t/standardize-references-to-desktop-linux/387
=> Consistent references to "Linux"

docs/email.en.md
=> fix typo in Email Services

docs/desktop.en.md
- [x ] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x ] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x ] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.
Looks like Fedora [rejected](https://pagure.io/fesco/issue/2711) fs-verity in F37.
=> Update Fedora description

docs/email-clients.en.md
From discussion https://github.com/privacyguides/privacyguides.org/discussions/1340
=> Warning about k-9 reply mailing list

docs/frontends.en.md
=> Fix typo in frontends page

docs/frontends.en.md
I think this reads a little bit better.
=> Fix grammar on LibreTube entry

docs/vpn.he_IL.md
=> fix vpn build

docs/assets/stylesheets/home.css
Attempt to fix the black line on Brave browser. Resolves #1701
=> Fix Black Line on Brave

docs/android.en.md, docs/basics/account-creation.en.md, docs/basics/passwords-overview.en.md, docs/basics/vpn-overview.en.md, docs/encryption.en.md, docs/frontends.en.md, docs/router.en.md, includes/abbreviations.en.md
This includes the English changes in https://github.com/privacyguides/privacyguides.org/pull/1972
=> Fix mistakes in various files

docs/about/donate.md, docs/about/privacy-policy.md, docs/basics/vpn-overview.en.md, docs/index.en.md, docs/os/qubes-overview.en.md, docs/productivity.en.md, docs/real-time-communication.en.md, docs/tools.en.md
=> Remove nerd term "use case", fix typos

docs/desktop-browsers.en.md, docs/file-sharing.en.md, docs/frontends.en.md, docs/multi-factor-authentication.en.md, docs/news-aggregators.en.md, docs/productivity.en.md
Note: I did not change the [instance in the Linux distributions page](https://github.com/privacyguides/privacyguides.org/blob/main/docs/desktop.en.md?plain=1#L176), because it doesn't sound right
=> Use consistent language across articles for open-source

docs/cloud.en.md, docs/productivity.en.md
=> Fix MFA consistency in criteria

docs/basics/common-threats.en.md, docs/basics/passwords-overview.en.md
=> Add FR specific, multi languages context

docs/about/privacy-policy.en.md
=> Add french specific GDPR context

docs/about/services.en.md, docs/advanced/tor-overview.en.md, docs/basics/multi-factor-authentication.en.md, docs/os/linux-overview.en.md, netlify.toml
=> Use Invidious for Embeds

docs/assets/stylesheets/extra.css, docs/assets/stylesheets/home.css, docs/index.en.md, mkdocs.yml, theme/overrides/home.en.html, theme/partials/header.html
=> Correct mobile width issues

docs/notebooks.en.md
=> Joplin - Add biometrics note

Brewfile.netlify, config/mkdocs.common.yml, netlify.toml, theme/assets/stylesheets/extra.css, theme/partials/header.html
=> Enable asset optimization

docs/os/android-overview.md
=> Permissions and Tracking (Android)

config/mkdocs.en.yml, config/mkdocs.fr.yml, config/mkdocs.he.yml, config/mkdocs.nl.yml
=> Fix theme switcher

config/mkdocs.common.yml, docs/email.md, docs/tools.md, docs/vpn.md
Avoiding admonition overuse.
This also makes WKD a requirement for the first email provider category, moves Startmail to the second category (since it does not support WKD), and moves ProtonVPN below IVPN and Mullvad because they don't accept Monero and their clients appear to just be objectively worse according to our own criteria.
=> Redesign larger pages

docs/email.md
I'm into keeping this info on the site but I don't like it being its own section, because it isn't a part of our criteria, and it seems to basically only serve to give mailbox.org bonus points which feels unnecessary. This moves it to the additional functionality heading.
=> Remove digital legacy heading

.github/workflows/pages.yml, .github/workflows/release.yml, config/mkdocs.offline.yml, docs/email.md, includes/abbreviations.en.txt, theme/main.html, theme/overrides/home.en.html
This adds an offline copy of the site to each GitHub release.
=> Enable offline builds

docs/email.md
Proton began supporting hardware 2FA keys on October 13, 2022 according to their blog post https://proton.me/blog/security-keys Updated the description to reflect allowing U2F hardware keys and linked to the documentation.
=> Updated Proton Mail - Account Security - U2F Now Supported

docs/desktop-browsers.md, docs/mobile-browsers.md
Add and fix annotations and correct the IPFS menu title for consistency. Also added the Always use secure connection toggle to mobile-browsers.md.
=> Brave corrections, additions and fixes

docs/multi-factor-authentication.md
- Require source code availability (as opposed to a distinct open-source requirement) for MFA apps
Context: https://discuss.privacyguides.net/t/raivo-otp-is-not-open-source/12198/10?u=jonah
=> Clarify source availability in MFA criteria

docs/tor.md
- Remove the recommendation to enable *Isolate Destination Address* in Orbot, which is not best practice
I think that was originally added in https://github.com/privacyguides/privacyguides.org/pull/390#issuecomment-993161651
---
> Isolating by destination address is also ridiculously expensive and
> slow if you're doing typical HTTP usage, or some other protocol where
> a single logical request turns into requests to many different hosts.
> Mike's got a more sophisticated approach here that he's aiming to do
> in TB; he can link to the best explanation of it better than I can
> find out which one is best.
- https://lists.torproject.org/pipermail/tor-talk/2012-May/024403.html
> Usually, unless you know better, you are better off not using IsolateDestAddr or …
=> Don't recommend Orbot IsolateDestAddr

docs/desktop-browsers.md
- Updated the headers to reflect the current browser UI locations
- Added Firefox Suggest note
- Added note about Brave's Web3 features
=> Browser configuration updates

Pipfile.lock, _redirects, config/mkdocs.common.yml, config/mkdocs.es.yml, config/mkdocs.fr.yml, docs/about/donate.md, docs/about/services.md, docs/cloud.md, docs/index.md, includes/strings.en.yml, netlify.toml, theme/assets/stylesheets/lang-he.css
=> Enable Spanish Translation

docs/frontends.md, docs/notebooks.md
=> Fix inconsistency

includes/strings.en.yml, theme/main.html
These notices are machine translated so we can merge this now, and then the string is added to Crowdin so we can get an actual translation for this notice from the team in the future.
=> Add translation notice to bottom of every page

docs/android.md, docs/basics/account-creation.md, docs/basics/email-security.md, docs/basics/threat-modeling.md, docs/basics/vpn-overview.md, docs/cloud.md, docs/cryptocurrency.md, docs/data-redaction.md, docs/desktop-browsers.md, docs/email.md, docs/encryption.md, docs/index.md, docs/mobile-browsers.md, docs/passwords.md, docs/real-time-communication.md, docs/search-engines.md, docs/tools.md, docs/tor.md, docs/vpn.md, theme/main.html
- Changes the `<title>` tags on our more popular pages to be more descriptive.
These changes are disabled on the international sites.
=> More descriptive title tags

docs/android.md
- Link to Auditor's supported devices list
=> Clarify Auditor's supported devices

Brewfile.preview.netlify, netlify.toml
- Only build the English site for Netlify deploy previews (performance, makes builds 4-6 minutes faster)
=> Disable Crowdin on Netlify PR Previews

docs/android.md
=> Remove Play Store link for shelter

docs/desktop-browsers.md
=> Add two missed asterisks for Bold

docs/basics/account-creation.md
- Changes "SSO" to "OAuth" and clarifies terms
I agree with https://matrix.to/#/!DxkgCpatedlzcEVBYu:aragon.sh/$Te_cHm7JEE0Uib_rJMHHq8SovfF7nE1ewLnb6UD7wxU?via=matrix.org&via=envs.net&via=tchncs.de
https://stormpath.com/blog/oauth-is-not-sso
=> Say OAuth instead of SSO

docs/tor.md
- Remove link to unofficial download for FreeBSD
- Remove Snowflake iframe and download links
=> Clean up tor page

docs/cloud.md
- Update Tresorit's description to "Swiss-Hungarian"
=> Update Tresorit jurisdiction

docs/desktop-browsers.md
- Remove outdated settings
closes #2163
=> Update Brave wallet settings

docs/email.md
- Remove criteria which states that email providers must be hosted outside the US.
This is discussed somewhat in https://discuss.privacyguides.net/t/skiff-mail-email-provider/11411. It's also [unclear](https://epic.org/ecpa/) whether the ECPA actually applies to emails anyways, I'm not aware of it being used in any relevant privacy attacks by the government...
The way this criteria is currently worded also makes it sound like the ECPA is a *bad* thing, in fact it would be *good* if the protections within the ECPA applied to email, but this has not been conclusively tested in case law. Worst case scenario it doesn't apply, and I'm not sure how that makes the US worse than anywhere else; best case scenario the protections within the ECPA *do* apply, which would …
=> Remove prohibition on US-based email providers

config/mkdocs.en.yml, config/mkdocs.es.yml, config/mkdocs.fr.yml, config/mkdocs.he.yml, config/mkdocs.nl.yml, config/mkdocs.offline.yml, docs/basics/why-privacy-matters.md, docs/tools.md
- Moves OS category in navbar to the bottom.
I think that operating systems currently receive a disproportionately high amount of consideration when people are considering privacy tools. The reality is that the many layers of tools you use _on top of_ your operating system have a _much greater_ day-to-day impact on your privacy than your operating system itself does (e.g. _generally, most people_ would be better off doing something like switching from Gmail to ProtonMail, rather than switching from LineageOS to DivestOS). 
Obviously they are still relevant to privacy, so of course we would continue covering them, but visually I would just like them to not be one of the first things we talk about. I think the current order also creates a feeling of "_oh, I have …
=> Deprioritize OS recommendations

Pipfile.lock, docs/vpn.md
https://mullvad.net/en/blog/2023/5/29/removing-the-support-for-forwarded-ports/
-
=> Mullvad removed support for port forwarding

.github/workflows/release.yml, docs/about/donate.md
This adds a link to the support us page so people can more easily find our merchandise.
=> Add HelloTux link to support us page.

docs/notebooks.md
- Fixes a broken link in the Standard Notes card
closes #2180
=> Fix Standard Notes Security Audit Link

includes/abbreviations.en.txt
=> Make digital legacy feature show up

docs/os/android-overview.md
=> Fix broken link to Shelter description

docs/basics/why-privacy-matters.md
- Change "tricker" to "trickier"
closes #2198
=> Fix typo in Privacy Matters page

docs/basics/account-deletion.md
=> Change Seahorse link

docs/mobile-browsers.md
=> Fix typo on mobile browser page

docs/tools.md, docs/vpn.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/2216
=> IVPN announces removal of port forwarding

docs/file-sharing.md, docs/productivity.md
=> Remove old BSD links

docs/os/linux-overview.md
=> Fix zram link

docs/os/linux-overview.md
=> Fix Phoronix links

docs/news-aggregators.md
=> Fix pronoun in Youtube RSS feed

docs/desktop.md
- docs/desktop.md: fix broken link
=> docs/desktop.md: fix broken link

config/mkdocs-common.yml, config/mkdocs-offline.yml, config/mkdocs.en.yml, config/mkdocs.es.yml, config/mkdocs.fr.yml, config/mkdocs.he.yml, config/mkdocs.it.yml, config/mkdocs.nl.yml, docs/meta/translations.md, includes/strings.en.yml, theme/main.html
By including this page hopefully translators will notice what might have been [buried in the blog article](https://blog.privacyguides.org/2023/02/26/i18n-announcement).
=> Translation page

Pipfile.lock, README.md, config/mkdocs-common.yml, theme/main.html, theme/partials/header.html
- Add `onion-location` meta tag
- Publish site to http://www.xoe4vn5uwdztif6goazfbmogh6wh5jc4up35bqdflu6bkdc5cas5vjqd.onion
=> Add onion-location header

docs/meta/translations.md
=> Re-write fullwidth part

docs/multi-factor-authentication.md
A simple grammar correction:
> If you are looking to store HOTP or TOTP ~~these~~ secrets, we highly recommend that you use a YubiKey instead.
---
=> MFA - Nitrokey HOTP/TOTP warning - correct sentence grammar

config/layouts/custom.yml, config/mkdocs-common.yml, config/mkdocs.ru.yml, netlify.toml, static/_redirects, theme/assets/stylesheets/lang-ru.css, theme/main.html
https://i18n-ru.staging.privacyguides.dev/ru/
=> Enable Russian Translation

docs/os/macos-overview.md
=> Fix typo in macos page

docs/email.md
- Correction about custom domain and catch-all addresses on Skiff Mail
- Resolves #2241
- [Custom domains, now free](https://skiff.com/blog/free-tier-custom-domain-launch)
=> Custom domain on Skiff Mail's free plan

docs/tools.md
=> Update links on Privacy Tools page.md

docs/desktop-browsers.md
the setting got renamed and moved to the shields section
=> Update Brave HTTPS setting

docs/desktop-browsers.md
=> Place Brave's Web3 settings on multiple lines

docs/vpn.md
- Closes https://github.com/privacyguides/privacyguides.org/issues/2249
=> Update countries VPN providers

docs/desktop.md
- Fix Fedora Workstation and Fedora Silverblue links
=> Fix Fedora links

docs/desktop.md, docs/os/qubes-overview.md
- Update terminology used to refer to ***qubes***
- Closes: https://github.com/privacyguides/privacyguides.org/issues/2210
=> Update Qubes Overview and Desktop/PC pages: use qube not VM

theme/assets/stylesheets/extra.css
Credits to https://heydon.github.io/Inclusive-Components/cards-pseudo-content/
- Closes #2202
=> Make list item clickable

docs/cloud.md
- Adding a link to the Windows Proton Drive app
=> Add Proton Drive Windows

docs/financial-services.md
- MySudo's virtual cards are only available via the iOS app currently, so Privacy guides should note that.
=> Update financial-services.md with note about MySudo's iOS exclusivity

docs/news-aggregators.md
- https://discuss.privacyguides.net/t/feeder-repository/14068/2
=> Update feeder repo url

docs/os/ios-overview.md
- Remove bogus link from iOS page.
Discussion: [14048](https://discuss.privacyguides.net/t/clarence-thomas-infiltrates-privacy-guides/14048)
=> Remove bogus link

Pipfile.lock, config/mkdocs-common.yml, theme/assets/stylesheets/home.css, theme/partials/footer.html, theme/partials/header.html, theme/partials/path-item.html, theme/partials/path.html
- Update `mkdocs-material-insiders`
=> Update mkdocs-material and dependencies

docs/email.md
- Update Tutanota aliases information
Closes: #2284
=> Update Tutanota aliases

docs/real-time-communication.md
- Update SimpleX chat client support [status](https://simplex.chat/downloads/#desktop-app) ([archived](https://web.archive.org/web/20230926133413/https://simplex.chat/downloads/#desktop-app))
=> Update SimpleX chat now supports MacOS and Linux

docs/advanced/dns-overview.md
=> Provide example of QNAME minimization

docs/basics/vpn-overview.md
- fix link to common misconceptions/known identity from VPN Overview
=> fix link to common misconceptions/known identity from VPN Overview

docs/email.md
- fixes indent in the marketing criteria section in email.md
=> Fix indent in email marketing criteria

docs/os/macos-overview.md
- Update MAC randomization information
- Remove unnecessary security info section
=> MAC address randomization update

docs/calendar.md
- Source: https://proton.me/calendar
=> Add Proton Calendar App Store link

docs/android.md
- Now that Google Pixel 8 is released it also comes with 7 years of OS upgrades and 7 years of security updates
Also makes price easier to justify:
https://github.com/privacyguides/privacyguides.org/blob/387f191ba99f7f3e0afd6906aa8b01811d9c9443/docs/android.md?plain=1#L193
=> Update pixel updates to 7 years

docs/basics/why-privacy-matters.md
- change links from github.com/privacytools/privacytools.io to code.privacyguides.dev/privacyguides/privacytools.io
=> Link to code.privacyguides.dev archive

docs/android.md, docs/email-clients.md, docs/news-aggregators.md, docs/tor.md
- Change feeder URL to the active repository.
- Change TOR URLs from gitweb to gitlab.
- Change K-9 mail URLs from https://github.com/k9mail/k-9 to https://github.com/thundernest/k-9
- Add Privacy Policy for Aurora Store
=> Update and Add URLs

docs/email.md
=> Tuta now supports subfolders

docs/os/android-overview.md
- Clarity in accuracy, fixes #2233
=> Clarify Google Play Services permissions

docs/CODE_OF_CONDUCT.md
=> Code of Conduct updated grammar and punctuation

docs/dns.md
Changes proposed in this PR: Supported as of December 15, 2020. See here: https://adguard-dns.io/en/blog/dns-over-quic.html
-
=> AdGuard supports DoQ

docs/notebooks.md
- Notesnook local encryption only available with Pro plan
https://matrix.to/#/!tNknizqbXcRXpKLkgM:privacyguides.org/$eVnDI7rpBMTcHn5gagEvMAX__Qm5J41JbALYREM705A?via=polarbear.army&via=matrix.org&via=tchncs.de
=> Clarify Notesnook encryption

docs/cloud.md
- Added Proton Drive [macOS](https://proton.me/blog/proton-drive-mac-app) download
=> Add Proton Drive macOS download

docs/notebooks.md, docs/real-time-communication.md
=> Fix dead links

docs/desktop-browsers.md
- Include a recommendation to enable forgetful browsing when using Brave
- https://discuss.privacyguides.net/t/recommend-forgetful-browsing-option-in-brave/14572
=> Include forgetful browsing recommendation for Brave

docs/vpn.md
- Modify server count for all VPNs recommended by Privacy Guides (IVPN, ProtonVPN and Mullvad). The server count made by this pull request has been last checked in the 21st of December 2023.
=> Update server count for VPNs

docs/vpn.md
- Update warning label in accordance with our [new advice](https://www.privacyguides.org/en/advanced/tor-overview/#safely-connecting-to-tor):
> If you have the ability to access a trusted VPN provider and any of the following are true, you almost certainly should connect to Tor through a VPN
=> Update VPN warning label

docs/vpn.md
- Closes: https://github.com/privacyguides/privacyguides.org/issues/1991
=> Add section on censorship circumvention

docs/email.md
- https://discuss.privacyguides.net/t/skiff-adds-pgp-as-beta-feature/15661/9?u=jonah
=> Skiff Mail added WKD/OpenPGP support

docs/vpn.md
- Note that Stealth is unavailable on Windows/Linux
=> Proton VPN Stealth availability

docs/calendar.md
- https://discuss.privacyguides.net/t/proton-calendar-is-not-open-source-mobile/14656/8?u=jonah
=> Note Proton Calendar's source availability

docs/vpn.md
=> Update Stealth Protocol VPN

docs/os/ios-overview.md
- Note https://support.apple.com/en-us/HT212510
=> Stolen Data Protection in iOS 17.3

docs/news-aggregators.md
- https://discuss.privacyguides.net/t/suggestions-for-news-aggregation-page/16012
=> Fix Reddit RSS syntax

docs/real-time-communication.md
- Convert the "Real-Time Communication" page, a.k.a. Messengers to use the new HTML admonitions.
=> Convert the Messengers page to HTML admonitions

docs/real-time-communication.md
Mention other matrix clients exist
=> Mention other matrix clients exist

docs/basics/threat-modeling.md
Writing error : 
Missing some words in the modified paragraph where the sentence could end like this "...after you're done writing / with it."
-
=> Clarify meaning of sentence in threat modeling guide

docs/photo-management.md
- Fixed incorrect Google Play link for Stingle Photos
=> Fixed incorrect link for Stingle Photos

docs/news-aggregators.md
- Changes required to make this work with Crowdin https://www.privacyguides.org/en/meta/admonitions/
=> Convert News Aggregators to HTML admonitions

docs/email-clients.md
- Convert "Email clients" page to HTML admontions
=> Convert "Email clients" page to HTML admontions

docs/android.md
- https://discuss.privacyguides.net/t/removed-page-link-at-android-page/16525
=> Fix broken blacklisting link (html admonition)

docs/calendar.md
- Convert Calendars page to HTML admonitions
=> Convert Calendars page to HTML admonitions

docs/cloud.md
- Convert Cloud storage page to HTML admonitions
=> Convert Cloud storage page to HTML admonitions

docs/financial-services.md
- Convert Financial Services page to HTML admonitions
=> Convert Financial Services page to HTML admonitions

docs/router.md
- Convert routers page to HTML admonitions
=> Convert routers page to HTML admonitions

docs/desktop-browsers.md
- Convert Desktop browsers page to HTML admonitions
=> Convert Desktop browsers page to HTML admonitions

docs/search-engines.md
- Convert Search Engines page to HTML admonitions
=> Convert Search Engines page to HTML admonitions

docs/desktop.md
- Convert Desktop PCs page to HTML admonitions
=> Convert Desktop PCs page to HTML admonitions

docs/mobile-browsers.md
- Updated the settings for Safari to reflect changes in iOS 17
=> Update Safari settings for iOS 17

docs/desktop.md
- https://discuss.privacyguides.net/t/broken-fedora-workstation-icon-after-v3-20-1-update/16752/3
=> Fix fedora workstation logo

docs/encryption.md
- Convert Encryption Software page to HTML admonitions
=> Convert Encryption Software page to HTML admonitions

docs/desktop.md
- https://discuss.privacyguides.net/t/consider-mentioning-video-memory-issues-that-tails-has/379
This is a very old suggestion (2022!) but nobody actually pulled off a PR for that, so there we go.
=> Mention video memory clearing on Tails

docs/mobile-browsers.md
- Convert Mobile Browsers page to HTML admonitions.
=> Convert Mobile Browsers page to HTML admonitions

docs/real-time-communication.md
https://signal.org/blog/phone-number-privacy-usernames/
https://discuss.privacyguides.net/t/signal-usernames-are-available-today/16995
=> Add Signal username information

netlify.toml
- https://developers.google.com/privacy-sandbox/relevance/topics/developer-guide#site-opt-out
=> Add Permissions-Policy HTTP header

docs/cryptocurrency.md
- Convert Cryptocurrency page to HTML admonitions
=> Convert Cryptocurrency page to HTML admonitions

docs/news-aggregators.md
- Fix broken Miniflux recommendation card (News Aggregators)
=> Fix Miniflux recommendation card

docs/data-redaction.md, docs/dns.md, docs/multi-factor-authentication.md, docs/tools.md, docs/tor.md, docs/vpn.md
- Convert : 
- "DNS providers" page
- "Data redaction" page
- "2FA" page
- tools.md file
- "Tor" page
- "VPN providers page"
To HTML admonitions.
There are, as far as I know, only 4 pages remaining! (at least in the recommendations)
=> Convert 6 pages to HTML admonitions

docs/news-aggregators.md
- removed closing </details> tag with no opening tag
=> Fix downloads for Miniflux

docs/multi-factor-authentication.md, docs/photo-management.md
- Add info about self-hosting
- Add audit from [Fallible](https://ente.io/reports/Fallible-Audit-Report-19-04-2023.pdf)
- Change GitHub download link to https://github.com/ente-io/ente/releases
closes #2421
=> Update ente card

config/mkdocs-common.yml, docs/dns.md, theme/assets/javascripts/randomize-element.js, theme/main.html
- Randomizes DNS table order (in JavaScript)
=> Randomize DNS table order

docs/vpn.md
=> Update VPN countries count

docs/android.md, docs/calendar.md, docs/cloud.md, docs/cryptocurrency.md, docs/data-redaction.md, docs/desktop-browsers.md, docs/dns.md, docs/email-clients.md, docs/encryption.md, docs/file-sharing.md, docs/financial-services.md, docs/frontends.md, docs/mobile-browsers.md, docs/multi-factor-authentication.md, docs/news-aggregators.md, docs/notebooks.md, docs/passwords.md, docs/photo-management.md, docs/productivity.md, docs/real-time-communication.md, docs/router.md, docs/search-engines.md
- removed "this section is new" admonitions since newly added sections and multiple other older ones
=> Remove "this section is new" admonitions to be in line with newer sections

docs/multi-factor-authentication.md
- Ente Auth has now desktop apps available for all platforms
=> Ente Auth has now desktop apps available for all platforms

docs/multi-factor-authentication.md
- Reverts 6aa14e8eb10dc915d9f2e2210fb0ec7aa93ae2bd and hopefully we can address https://github.com/privacyguides/privacyguides.org/pull/2453#issuecomment-2027723201 this time around! 🤨
=> Revert "Ente Auth desktop apps on all platforms (#2453)"

README.md
=> Fix GitHub README logo

.github/workflows/build.yml, config/layouts/page.yml
=> Hebrew language build fix

.github/workflows/build-offline.yml, .github/workflows/build.yml, .github/workflows/test-build.yml
The GitHub workflow is not pulling in translations properly, this should fix.
=> Fix language build environment variables

.github/workflows/deploy.yml, .github/workflows/publish-release.yml, package-lock.json
- Host website on BunnyCDN (simultaneously hosting on Bunny & Netlify to compare)
=> Deploy releases to BunnyCDN

docs/basics/account-creation.md, docs/financial-services.md, docs/os/ios-overview.md
- Update links so that they point to the new Email Aliasing page
=> Update email aliasing links

config/mkdocs-common.yml, theme/assets/javascripts/feedback.js, theme/assets/javascripts/resolution.js, theme/main.html
Results visible at https://stats.privacyguides.net/share/nVWjyd2QfgOPBhMF/www.privacyguides.org
=> Bring back feedback buttons

docs/frontends.md
- Piped
- Change the "Public Instances" link for Piped to match the one in the Warning admonitions under the [Yattee card](https://www.privacyguides.org/en/frontends/#yattee) and the [LibreTube card](https://www.privacyguides.org/en/frontends/#libretube-android)
- Update link to Piped docs (current one is broken)
- LibreTube
- Change link to LibreTube's privacy policy (new link is a more complete version of the current one)
- Add donation link for LibreTube
- Update link to LibreTube homepage
=> Update links on Frontends page

docs/CODE_OF_CONDUCT.md, docs/basics/account-deletion.md
- Correct grammatical errors on the Code of Conduct page
- Update aliasing link that I overlooked in https://github.com/privacyguides/privacyguides.org/pull/2480 :sweat_smile:
=> Make grammar changes on Code of Conduct page

docs/email.md
- Update Tuta links on the Email Services page (some of the current ones are broken)
- Remove mention of Secure Connect as it looks like Tuta discontinued this service
- The "Secure Connect" link in this [section](https://www.privacyguides.org/en/email/#additional-functionality_2) of the Tuta recommendation is broken. Their [business page](https://tuta.com/business) and support center do not have any mention of it, and a Reddit thread on the Tuta sub shares an email warning its customers about the discontinuation of Secure Connect.
https://old.reddit.com/r/tutanota/comments/16ik6ni/closest_replacement_for_for_secure_connect_since/
(These changes are a continuation of https://github.com/privacyguides/privacyguides.org/pull/2489, but warrant a separate PR.)
=> Update Tuta links

docs/search-engines.md
- https://discuss.privacyguides.net/t/startpage-is-now-accesible-over-tor-onion/17759
=> Add Startpage hidden service address

docs/encryption.md
moved to their own site 
https://github.com/dyne/Tomb/commit/0c8d4cf4774e62dc559245e215458f1ce89f2320
and it is now in "Advanced usage" section.
=> Update tomb steganography link

docs/frontends.md
Add that website mandating an account and blocking VPNs can also be included. We may also include website that block TOR, but that would significantly escape it's scope, as a lot of websites block TOR．
=> Broaden frontend software criteria

docs/dns.md, docs/tools.md, docs/vpn.md
- Remove redundant criterion in the "Technology" section of the VPN provider criteria, as suggested here: https://discuss.privacyguides.net/t/require-both-wireguard-and-openvpn-support-in-vpn-criteria/16269/2
- Mention that IVPN also [does not offer a free trial](https://www.ivpn.net/knowledgebase/billing/does-ivpn-offer-a-free-trial/)
- Remove comparative language about Mullvad's lack of 2FA in the IVPN section since the recommendations on this page are [not ordered](https://discuss.privacyguides.net/t/are-privacy-guides-recommendations-ordered/16912/4)
- Remove redundant line about Mullvad's onion address in "Additional Notes" as it is already present in the recommendation card
- Update link to gopass in `tools.md` as a result of the changes to the gopass …
=> Standardize language on VPN Services page

.github/workflows/build-container.yml, .github/workflows/build.yml, .github/workflows/test-build.yml, .github/workflows/test-lint.yml, .vscode/settings.json, docs/about/statistics.md, docs/cloud.md, docs/email-aliasing.md
- Preview: https://github.com/privacyguides/privacyguides.org/blob/c670e5f30074eb44b31ad5f8a086ff4927b8ea5b/README.md#mirrors
- Also fixed two broken links on the site
- https://discuss.privacyguides.net/t/mirroring-publishing-privacy-guides-to-decentralized-networks/17565
=> Link to mirrors in README

docs/email.md
- Closes https://github.com/privacyguides/privacyguides.org/issues/2508
=> Email: Mention free Proton account deletion

docs/email.md
- Edit Proton Mail recommendation card (500 MB storage --> 1 GB storage) & better wording about crash reports
=> Edit Proton Mail recommendation card & better wording

docs/basics/common-threats.md
- Change "strategues" to "strategies"
=> Fixed typo in common-threats.md

docs/email.md
- Add comparison table for the Email Services page
<del>  - As marked on GitHub, this is a draft PR as wording and formatting is not set in stone. I'm unsure of what to rearrange, add, or remove, so any feedback is welcome. Here is a question as a starting point:</del>
<del>    - **Table Columns**: Are there any criteria that should be added to or removed from the current table?</del>
- Alter wording about Proton and Tuta's free plans for [clarity](https://github.com/privacyguides/privacyguides.org/pull/2512#discussion_r1560439458)
- https://proton.me/support/more-storage-proton-drive
> The **default** Proton Mail free storage is **500 MB**, and you can receive an _additional 500 MB_ [1 GB total] upon completing the Proton Mail-specific initial actions …
=> Add email service comparison table

docs/cloud.md, docs/notebooks.md
- Append Proton Drive free storage infomation.
- Append Standard Notes infomation that Standard Notes has joined Proton AG as of April 10, 2024.
=> Append Proton Drive free storage infomation.

docs/notebooks.md
- Update Web Application for Notesnook in Notebooks section.
<summary>
</details>
=> Update Web Application for Notesnook in Notebooks section.

docs/photo-management.md
- Append free trial infomation of Ente.io at Photo Management.
<summary>
</details>
=> Append free trial infomation of Ente.io at Photo Management.

docs/mobile-browsers.md
- https://discuss.privacyguides.net/t/proposal-drop-gecko-browsers-on-android-due-to-security-concerns-and-add-reasoning/17840/68
- https://discuss.privacyguides.net/t/proposal-drop-gecko-browsers-on-android-due-to-security-concerns-and-add-reasoning/17840/70
<summary>
4) I agree to the …
=> Revise notes on Mull/GeckoView Android

docs/productivity.md
- Move the criteria established for paste services (which were added in #2165) so that it falls under the "Paste services" heading
- <del>Add provisional criteria for language services (using the criteria on the [Email Aliasing](https://www.privacyguides.org/en/email-aliasing/#criteria) page as a reference) as a stopgap until the productivity criteria is modified per https://github.com/privacyguides/privacyguides.org/pull/2013#issuecomment-2055253809</del> Formal criteria for the Language services section was added per the [comment](https://github.com/privacyguides/privacyguides.org/pull/2548#issuecomment-2059578921) below.
<summary>
2) I agree to grant …
=> Move paste services criteria and establish language services criteria

docs/basics/common-threats.md
- remove leftover brackets
<summary>
</details>
=> remove leftover brackets

docs/notebooks.md
Added Flathub link for Notesnook. 
-
<summary>
- [ X] I agree to the terms listed below:
</details>
=> Add Flatpak link for Notesnook

docs/vpn.md
- mention of prepaid cards at Mullvad
<summary>
</details>
=> Mention that Mullvad accepts prepaid cards

docs/basics/multi-factor-authentication.md, docs/device-integrity.md, docs/encryption.md, docs/tools.md
- Note iVerify's rebranding of their consumer app and changes in functionality
- Minor: Fix some build warnings
<summary>
</details>
=> iVerify Basic downgrade info

docs/multi-factor-authentication.md, docs/photo-management.md, docs/tools.md
- Capitalize all instances of ente -> Ente
- Change 'Ente' to 'Ente Photos' to better reflect the difference from other Ente products
- Update the free tier storage info from 1GB to 5GB [[Source]](https://mstdn.social/@ente/112428405587772437)
<summary>
4) I agree to the Community Code of …
=> Update information for Ente

docs/basics/email-security.md
- Fix typo in Email Security page (email-security.md)
<summary>
</details>
=> fix: typo in Email Security page (email-security.md)

docs/dns.md, docs/os/android-overview.md
- Android Overview
- Remove mention of RethinkDNS from the following sentence (for the reason, see the next section on the changes to the RethinkDNS recommendation):
> RethinkDNS, TrackerControl and AdAway in non-root mode will take up the VPN slot (by using a local loopback VPN) preventing you from using privacy enhancing services such as Orbot or a real VPN server.
- Add internal link to Orbot card
- Reword two sections for increased clarity
- Make minor grammar changes otherwise not noted above
- DNS Resolvers
- Mention that RethinkDNS supports Wireguard and Orbot configurations in the app and link documentation for both
- This renders the part of the quoted statement about RethinkDNS preventing you from using Orbot or a VPN incorrect.
- Reword RethinkDNS …
=> rethinkdns: Mention that the app supports Wireguard and Orbot configs

docs/android.md, docs/os/ios-overview.md
- iOS Overview
- Update Find My description
- Closes #2609 
- Modify "custom Android operating system" internal link to point to a more specific section
- Rename "stolen data protection" to "Stolen Device Protection" to properly reflect the name of the [feature](https://support.apple.com/en-us/HT212510)
- Make minor grammar changes otherwise not noted above
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of …
=> ios-overview: Update Find My description

docs/desktop-browsers.md
- Update the guidance for Extensions in the Brave configuration
- The [most recent Brave update](https://github.com/brave/brave-browser/releases/tag/v1.67.115) enables the "Media Router" extension by default on new profiles. I figure that simplifying the guidance (similar to "Uncheck all social media components") is more desirable than listing the settings to disable because it'll lead to fewer revisions to this section if Brave adds or enables more extensions in the future.
- Apply specific [guidance about the language for requirements](https://www.privacyguides.org/en/meta/writing-style/#use-must-for-requirements) from the Writing Style page to the criteria for desktop browsers
- Italicize names of settings (settings to be changed remain bolded)
<summary> …
=> desktop-browsers: Update Brave configuration and apply writing style to criteria

Pipfile.lock, theme/main.html
- https://github.com/mastodon/mastodon/pull/30398
<summary>
</details>
=> Add `fediverse:creator` OpenGraph tag

docs/os/ios-overview.md
- Added a new section that guides users to Location Services -> System Services, allowing them to customize which system services they want to have location enabled for if they choose to leave it on.
- Additionally, clarified that users can also scroll down and stop location analytics data from being sent to Apple to be used to improve Apple Maps, which was not previously included in the privacy recommendations
- Added additional information about Location Services which was not there previously, which is below:
- Clarified that a purple arrow indicates an item has used location recently, while a grey arrow indicates an item has used location within the last 24 hours
- Also added that App Tracking is disabled for Apple users under the age of 18
<summary> …
=> iOS Location Services Clarifications

docs/meta/commit-messages.md
- a more comprehensive standards to base future PR commit messages on
<summary>
</details>
=> docs: Update Git commit message guidelines

docs/device-integrity.md
- Device Integrity page
- Fixes #2645 
- Make minor grammar fixes and changes for improved readability 
<summary>
</details>
=> fix: Replace iVerify Basic homepage link

docs/passwords.md
- remove open source from the description as per https://github.com/strongbox-password-safe/Strongbox/issues/784
closes #2649 
<summary>
</details>
=> fix: Remove Open Source from Strongbox

docs/cryptocurrency.md, docs/financial-services.md, docs/tools.md
- Financial Services
- Update the description of Privacy.com's paid plans in light of the recent introduction of a new paid plan: https://privacy.com/blog/introducing-privacy-plus-plan
- Cashback isn't available in this new plan, so I removed the mention of it altogether
- Remove the information about country availability in the Coincards description (as the service is available in countries other than the U.S. and Canada now) and replace it with a sentence that directs readers to the service's homepage which provides this information at a glance
- Cryptocurrency
- Remove mention of Cake Wallet's Linux _beta_ app
- Generally, Privacy Guides waits for software or services to exit beta into a stable release before evaluating them (here's the [most recent …
=> update: Update Financial Services and Cryptocurrency pages

docs/desktop-browsers.md
- update brave's settings to align with the current layout
closes #2657 
<summary>
</details>
=> fix: Update brave browser settings

docs/cloud.md
=> fix: sdi links

theme/home.html
- handle no-JS better on homepage
<summary>
</details>
=> feat: Add noscript fallback to homepage

docs/cloud.md, docs/photo-management.md
- Photo Management
- Update the description about Ente's free plan per the recent [announcement](https://ente.io/blog/pricing-update/) on their blog
- Move the information about Ente's audits to the space below the card so that its consistent with the way audits of other products are positioned on the site
- Remove redundant criterion on this page, as discussed in https://discuss.privacyguides.net/t/photoprism-does-not-meet-minimum-requirements/18994/6
- Remove the same redundant criterion on the Cloud Storage page
- Reasoning: The listed providers on the Cloud Storage page all support E2EE, so the first minimum requirement already covers this.
> Must enforce end-to-end encryption.
- Make minor wording changes otherwise not noted above
<summary> …
=> fix: Update Ente Photos description and remove redundant criterion

docs/index.md, docs/tools.md, mkdocs.yml, run.sh, theme/home.html
- more informative main pages
<summary>
</details>
=> feat!: Homepage and tools page redesigns

docs/os/linux-overview.md
- Closes: https://github.com/privacyguides/privacyguides.org/issues/1861
- Closes: https://github.com/privacyguides/privacyguides.org/issues/2008
The intention of this PR is to explain what mandatory access control is, and how technologies like Snapd use it to confine apps. For further direct confinement, mention [ConfinedUsers](https://fedoraproject.org/wiki/SIGs/ConfinedUsers).
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my …
=> update: Mandatory access control explainer

docs/vpn.md
- update: update country count of VPN providers
<summary>
</details>
=> update: VPN provider country count

docs/about.md
=> Add Fast Company coverage.

docs/tools.md
`tools.md`
- Apply the changes in #2698 to this page
- Reword "VPN Software" to "VPN Providers" for this [reason](https://github.com/privacyguides/privacyguides.org/pull/2680#issuecomment-2263763955)
<summary>
</details>
=> update: Update VPN country count on `tools.md`

docs/real-time-communication.md
- update: Mention that you can modify the digits of your Signal username
<summary>
</details>
=> update: Mention that you can modify the digits of your Signal username

docs/email.md
- As discussed in the team chat, mention audits in the best-case criteria for email services
- The added line is the same as the one in the [minimum requirements](https://www.privacyguides.org/en/vpn/#security) section for VPN providers
- Unbold the founding years of Proton Mail and Tuta to match how they're formatted on the homepage
- Add "(formerly _Tutanota_)" in the Tuta card to match its description on the homepage
- Replace the lengthy WebAuthn explanation in the best-case security criteria with an internal link to the FIDO2 section on the MFA Knowledge Base page
- Reasoning: This is mostly an effort of de-duplication, as the information here is also present on the aforementioned Knowledge Base page.
- Remove excess empty lines to attempt to resolve …
=> update: Add third-party audits to best-case email provider criteria

docs/real-time-communication.md
- Element
- Revert #2377 in light of the conclusion reached in this forum thread: https://discuss.privacyguides.net/t/remove-matrix-element-mentions-from-real-time-communication/20068/22
- Replace the word "reference" with "flagship" to describe Element's status as a Matrix client
- Reasoning: I think that "[flagship](https://dictionary.cambridge.org/dictionary/english/flagship)" is a more precise choice of wording here because it indicates that Matrix is connected to the ownership or production of the client (which [it is](https://element.io/matrix-benefits)).
- Re-format the excerpt from Session's audit so that it's consistent the way audits are formatted elsewhere on the site (e.g., on the [VPN Services](https://www.privacyguides.org/en/vpn/#independently-au …
=> update: Remove mention of Matrix clients other than Element

docs/about.md, docs/about/donate.md, docs/about/jobs.md, mkdocs.yml, run.sh, theme/main.html
- https://github.com/MAGICGrants/MagicGrants.org/pull/2
- adds donation banner
<summary>
</details>
=> docs: Add employee information

README.md
- just a small update to readme.md
<summary>
</details>
=> docs: Add Fast Company mention to README.md

docs/android/distributions.md
- https://github.com/privacyguides/privacyguides.org/pull/2722#pullrequestreview-2249273061
<summary>
</details>
=> update: Remove DivestOS warning

docs/file-sharing.md, docs/passwords.md
- Briefly mention Bitwarden Send and Proton Drive's file sharing functionality in the introduction to the File Sharing section on the page with the same name
- Relevant discussion: the latter part of https://discuss.privacyguides.net/t/improvements-to-the-file-sharing-and-sync-section/186/9
- Move the Bitwarden Send description from the Password Managers page to a footnote on the File Sharing page
- This means deleting the Send description under the Bitwarden card. My reason for this is to keep tool descriptions discrete and focused: If readers want to explore file sharing options, then they will be on the appropriate page. If readers want to explore password manager options, then they too will be on the appropriate page.
- Apply specific [guidance about the …
=> update: Briefly mention Bitwarden Send and Proton Drive on File Sharing page

docs/email-aliasing.md, docs/email.md
- Email Aliasing recommendation page
- Add subscription termination information to the Email Aliasing page
- Relevant discussion: https://discuss.privacyguides.net/t/add-subscription-termination-info-to-email-aliasing/19208
- I also think that there's little reason _not_ to include this information since a similar section is included for each provider on the Email Services page. Also, for a provider like addy, the end result of subscription termination is the same as that of account termination for e.g. Proton Mail: not receiving emails.
- Remove part of the addy.io description which states that unlimited standard aliases "are less anonymous"
- Reason: There is already a more detailed description of the limitation of this type of alias under the card.
- …
=> update: Add subscription termination info to Email Aliasing

docs/about/executive-policy.md, mkdocs.yml
- Publish our first true executive policy as described in https://github.com/MAGICGrants/MagicGrants.org/pull/3 on our own website.
=> docs: Executive policy page

docs/about/criteria.md
- Add participation in the developer self-submission process (aka [Project Showcase](https://discuss.privacyguides.net/t/about-the-project-showcase-category/114)) as a requirement
- It was briefly mentioned in the WIP [volunteer's handbook](https://github.com/privacyguides/privacyguides.org/pull/2700/files#diff-6f3b626aafb1ea347b16df5d199d2969f81a21a5f6d7c220e205d2f9078e69faR53-R59), but I think it's pertinent to mention on the General Criteria page as well.
- Add link to the Common Threats page to provide inspiration for developers when formulating the exact threat model for their projects
- Given the increased emphasis on threat modeling with the addition of threat model labels on a majority of tool pages, it might be good to nudge prospective developers …
=> docs: Expand on developer self-submission requirements

blog/posts/proton-wallet-review.md
- For the recent blog post "Proton Wallet Review: Is Proton Losing Touch?" I've added links to Proton Mail and Proton VPN's recommendation pages on PG, using permanent links. This way, it's easier for users to access the recommended services without having to search for them manually.
=> update(blog): Add links to Proton Mail and Proton VPN

docs/mobile-browsers.md
- https://discuss.privacyguides.net/t/brave-ios/20137
=> update: Recommend Brave on all platforms

blog/author/dngray.md, blog/editorial.md, mkdocs.blog.yml, theme/blog-post.html
- Publish transparency policies related to https://thetrustproject.org/#indicators
=> docs(blog): Publish editorial policy for news articles

docs/mobile-browsers.md, docs/tools.md
- Updated description since Safari already blocks tracker by default
- Added fingerprint randomization
- Updated tools description. Content blockers aren't mentioned in the other browsers so I removed that. Also added mention of new features that are comparable to Firefox's anti-fingerprinting features.
=> update: Safari description

docs/advanced/tor-overview.md
- replaced broken invidious links with YouTube links
=> fix: Replace Broken Invidious links with YouTube

docs/data-broker-removals.md
- Add direct search and opt-out links to high priority targets
- Add a tip on how to strategize your manual opt-outs effectively without burn out
- Add list of high priority sites not supported by recommended services
- Add criteria section
=> update: Add list of sites not supported by removal services

docs/frontends.md
- YouTube frontends
- Add note to the YouTube section of the Frontends page that briefly summarizes YouTube's API changes and suggests what readers can do if they find that one frontend is unreliable
- Relevant discussion: [[1](https://discuss.privacyguides.net/t/remove-libretube/20087/55)] [[2](https://discuss.privacyguides.net/t/remove-libretube/20087/64)]
- I think that this is the best way to move forward if one YouTube frontend exhibits reliability issues. The threat of YouTube making more API changes is a looming presence for these frontends, and frontend maintainers are doing their very best with their free time. Rather than remove a frontend because it doesn't work at the moment, I think it's more reasonable to ask readers to switch to another one. In …
=> update: Note YouTube's API changes and reorder YT frontends

docs/cloud.md, docs/encryption.md
- Add information about Picocrypt's recent audit
- Relevant discussion: https://discuss.privacyguides.net/t/picocrypt-security-audit-results/20615
- Correct the date of Peergos's [audit](https://peergos.org/posts/security-audit)
=> update: Add Picocrypt audit

docs/real-time-communication.md
- fixed stylistic inconsistency 
- added new July 2024 audit
- added more detailed info from the simplex website
closes #2776
=> update: Add more Simplex Chat info

docs/about.md
- updated my name and GitHub link
=> docs: Update @friadev's GitHub username

docs/passwords.md
- Update the GitHub releases link for Bitwarden in light of the stable release of its native Android app
- Relevant discussion: https://discuss.privacyguides.net/t/bitwarden-releases-phased-beta-for-native-mobile-apps-bitwarden-blog/19412/4
- In the gopass description, remove the list of operating systems it supports since the Downloads section already enumerates them
- Standardize syntax for [primary buttons](https://squidfunk.github.io/mkdocs-material/reference/buttons/#adding-primary-buttons)
- Make minor wording and style changes
=> update: GitHub releases link for Bitwarden

docs/mobile-browsers.md
- added suggestions for new options and reevaluated old ones
- fix Safari intro sentence to reflect that Brave is now recommended on iOS
closes #2797
=> update: iOS 18 Browser Recommendations Improvements

docs/desktop-browsers.md, docs/mobile-browsers.md
- Add guidance for disabling search suggestions in all versions of Brave
- Relevant discussion: https://discuss.privacyguides.net/t/firefox-and-brave-recommendations-are-incomplete-regarding-search-suggestions/10673
- Add context for block quote in the Telemetry section of the Firefox recommended config
- Standardize syntax for [tooltips](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-tooltips)
- Make minor wording and grammar changes
=> update: Include disabling search suggestions in browser configs

docs/encryption.md, docs/os/macos-overview.md, docs/tools.md
- Bring some of the changes from #2437 to a new PR with some changes, as the original author gave their permission to do so [here](https://github.com/privacyguides/privacyguides.org/pull/2437#issuecomment-2461144506)
- Reword the "OS Full Disk Encryption" heading to "Operating System Encryption"
- Reasoning: The original heading is not entirely accurate since BitLocker and FileVault are described as *full volume* encryption solutions underneath.
- Rework the introduction to the OS Encryption section of the Encryption Software page using @friadev's suggestion [here](https://github.com/privacyguides/privacyguides.org/pull/2437#discussion_r1819631096)
- In the FileVault card, replace the external link to Apple's docs with an internal link to the section …
=> update: Refine OS Encryption section

docs/real-time-communication.md
Explain how Session open group works. Current one is vague and lacking.
=> update: More detailed Session description

docs/about/statistics.md, theme/assets/javascripts/feedback.js
Link to https://stats.triplebit.net/share/S80jBc50hxr5TquS/www.privacyguides.org
=> fix: Correct broken statistics link

docs/about/jobs.md, docs/about/jobs/intern-news.md
Note that we are no longer accepting new applications for this position, as we have received a high volume of applications already.
=> docs: Close internship listing

docs/real-time-communication.md
- Adds a GitHub Releases download link to the Signal entry
=> update: Add Signal Android GitHub releases download link

docs/os/ios-overview.md
- Update and correct some parts of the Privacy Notes section in the iOS Overview
- Relevant discussion: https://discuss.privacyguides.net/t/ios-overview/20915
- Reword mentions of "anonymizing" and "anonymous" to better reflect the language in Apple's privacy policy
- Elaborate on the issue surrounding Siri recordings by mentioning the opt-out toggle and subsequent transition to on-device recording
- Add section about certain traffic on iOS not going through an active VPN connection
=> update: Privacy Notes section of iOS Overview

docs/meta/uploading-images.md
- Create a full ellipsis ("...")
- Show the sequence of options in drop-down menu
- Make clear what should be selected for type of file
=> docs: Fix typo & improve formatting in uploading-images.md

docs/data-redaction.md
- remove [metadata cleaner](https://gitlab.com/rmnvgr/metadata-cleaner) because it's labelled unmaintained by the maintainer
=> update: Remove metadata cleaner

blog/tags.md, mkdocs.blog.yml
=> style: Collapse blog sidebar navigation sections

docs/vpn.md
Source code gives transparency about what the program is doing, but _not_ what your device is doing.
=> style: VPN criteria source code better term

docs/cloud.md
- Add the link of the guide to get additional storage for Proton Drive
=> update: Add the link of the guide to get additional storage for Proton Drive

docs/advanced/payments.md, docs/cryptocurrency.md, docs/financial-services.md
-
The main change is adding some recommendations for where to buy Monero. This a list of various reputable places with different requirements (Kraken: KYC ok; Cake Wallet: avoid KYC; RetoSwap: P2P and no country restrictions).
I also added some sub-headings for wallets and nodes and put the comments about Monero's resilience in a summary+detail box.
Finally, some cross-linking between the advanced/payments.md and the cryptocurrency.md pages.
I have just written this in Markdown so hopefully the end result will render correctly. Also happy for to make changes, this is just a first draft.
=> update: Tidy up Cryptocurrency page and recommend places to buy Monero

mkdocs.yml
Capitalized Russian in the language selector
-
=> Capitalized Russian in the language selector

docs/android/distributions.md, docs/mobile-phones.md, docs/os/android-overview.md
- remove “custom ROM” as it’s an inaccurate term
- Remove AOSP derivatives as a category because they will all be AOSP derivatives anyway
=> update: Fix information on Android distributions page

.github/workflows/publish-blog.yml
- Release blog articles when changes to `/blog/**` are made instead of waiting for releases
=> ci: Release blogs immediately

blog/posts/choosing-the-right-messenger.md, blog/posts/delisting-startpage.md, blog/posts/delisting-wire.md, blog/posts/firefox-privacy-2021-update.md, blog/posts/firefox-privacy.md, blog/posts/mozilla-disappoints-us-yet-again-2.md, blog/posts/privacy-guides-partners-with-magic-grants-501-c-3.md, blog/posts/relisting-startpage.md, blog/posts/security-privacy-anonymity.md, blog/posts/the-trouble-with-vpn-and-privacy-review-sites.md, blog/posts/welcome-to-privacy-guides.md, blog/posts/weve-joined-the-open-collective-foundation.md, blog/posts/why-i-run-a-tor-relay.md, mkdocs.yml
- Add image credits to cover photos
- Fix #2851
=> update(blog): Add image credits to cover photos

blog/author/em.md
@EmAtPrivacyGuides please review your bio or edit it according to what you'd like shown on https://www.privacyguides.org/articles/author/em/
=> update(blog): Add Em's author bio

docs/email-aliasing.md
References:
https://proton.me/pass/pricing
=> update: Add Proton Pass Plus as another way of having SimpleLogin premium

docs/encryption.md
- Add info about the paid iOS and Android Cryptomator apps
closes #2863
=> update: add info about paid Cryptomator apps

docs/cloud.md
=> update: add second audit for peergos

docs/data-broker-removals.md
The company has apparently ceased operations, per their homepage.
=> update: Remove GladIKnow from data broker removal list

blog/author/dngray.md, blog/author/freddy.md
Missed the PR adding Em's bio :(
=> update(blog): Minor updates to author bios

docs/about.md, docs/cryptocurrency.md, docs/data-broker-removals.md, docs/email-aliasing.md, docs/mobile-browsers.md, docs/os/ios-overview.md
- Added mention of crypto payment and official ProxyStore
closes #2864
=> update: mention anonymous payment methods for SimpleLogin and addy.io

docs/vpn.md
- Add links to Mullvad and IVPN’s audits since the section keeps getting outdated.
Closes #2865
=> update: Add links to Mullvad and IVPN audits

videos/posts/5-easy-steps-to-protect-yourself-online.md
https://www.youtube.com/watch?v=x5bKUA2sVFM
Closes https://github.com/privacyguides/video-ideas/issues/4
=> update(video)!: 5 Easy Steps to Protect Yourself Online

blog/posts/installing-and-using-tails.md
Add link to the article: https://www.privacyguides.org/articles/2025/02/13/clearing-browsing-data/
=> update(blog): Add link to Clearing Browsing Data article

theme/blog-post.html
This adds a note to all articles older than **18 months**.
=> feat(blog): Add old article warning

docs/vpn.md
- Mullvad recently reduced their 30 day refund policy to [14 days](https://mullvad.net/en/blog/for-privacy-change-of-our-refund-policy-from-30-to-14-days)
=> update: Fix Mullvad's 30 day refund policy to 14 days

docs/about.md, docs/passwords.md
* Add link to download on macOS for Bitwarden
=> update: Add macOS download link for Bitwarden

videos/posts/why-you-need-tor.md
Closes https://github.com/privacyguides/video-ideas/issues/23
=> update(video)!: Anonymity for Everyone: Why You Need Tor

docs/desktop-browsers.md
=> update: Mullvad Leta is now available without restriction

docs/language-tools.md
- Reword introduction to the Language Tools page so that it reflects the changes in #2909 
Closes #2923
=> update: Reword introduction to Language Tools page for consistency

docs/tor.md
=> update: Note iOS limitations wrt Onion Browser

docs/privacy.md
Now that our unified privacy notice is put together, we can draft changes here.
=> docs: Privacy notice clarifications and updates

docs/tools.md, docs/vpn.md
Update Mullvad supported 49 countries at vpn.md.
=> update: Country count for Mullvad servers

docs/advanced/communication-network-types.md, docs/advanced/tor-overview.md, docs/basics/vpn-overview.md, docs/basics/why-privacy-matters.md, docs/index.md, docs/real-time-communication.md, docs/tor.md
- Adds links to videos in relevant contexts
- Removes recommended tools section from homepage
=> feat: Surface more videos across the website

docs/about/donate.md, generate-members.py
- Shows the number of active members on our donation page from https://github.com/MAGICGrants/campaign-site/pull/156 minus the number of public members on the forum
=> feat: Fetch membership count from MAGIC

blog/posts/the-privacy-of-others.md
Replaced "do to it" with "to do it"
=> style(blog): Fix typo in The Privacy of Others article

.vscode/ltex.dictionary.en-US.txt, docs/about/donate.md
https://magicgrants.org/2025/03/18/accepting-litecoin-and-mweb-donations.html
=> docs: Now accepting Litecoin MWEB donations

docs/basics/vpn-overview.md
- https://discuss.privacyguides.net/t/secure-encryption-and-online-anonymity-are-now-at-risk-in-switzerland/26181/28
=> update: Remove mention of specific MPRs

docs/vpn.md
- https://discuss.privacyguides.net/t/protonvpn-potentially-misleading-ui/26543
=> update: Note location of Proton VPN Android telemetry

docs/os/macos-overview.md
- Changed the commands to be more consistent with each other
=> style: Make commands in macOS page more consistent

docs/dns.md
- Update some links to signed Apple configuration profile
- Add HTML line breaks to data cells where appropriate
- Add line breaks to footnotes for more organized look
- Rearrange download links so mobile app downloads are first (consistent with listings on other recommendation pages)
- Apply writing style guidelines to criteria
Closes #2959
=> style: Reformat parts of DNS table and footnotes

blog/.authors.yml, videos/.authors.yml, videos/posts/is-privacy-dead.md
> https://www.privacyguides.org/en/basics/why-privacy-matters/
> https://www.privacyguides.org/en/tools/
> https://www.privacyguides.org/videos/2025/02/14/5-easy-steps-to-protect-yourself-online/
> 
> Gmail data collection: https://www.wired.com/story/google-app-gmail-chrome-data/
> What is the GDPR: https://www.cloudflare.com/learning/privacy/what-is-the-gdpr/
=> update(video): Add sources to latest video

docs/desktop-browsers.md, docs/tor.md
- Note: https://discuss.privacyguides.net/t/in-praise-of-tor-why-you-should-support-and-use-tor/27174/6
=> update: Note Tor Browser security level flaw

blog/posts/in-praise-of-tor.md
- Added warning to restart browser when changing the security level
=> update(blog): Add warning about browser restart

docs/frontends.md
- Updating the public instances URL for Invidious and Piped
=> update: Links to lists of public instances for Invidious and Piped

blog/posts/sam-altman-wants-your-eyeball.md, theme/blog-post.html, theme/layouts/blog.yml, theme/layouts/page.yml, theme/layouts/video.yml, theme/video-post.html
- Also includes minor fix from #3035
=> fix: Update OpenGraph tags

blog/posts/privacy-means-safety.md
- Fixed typo/grammar issue in "Privacy Means Safety" article
=> style(blog): Fix typo in "Privacy Means Safety" article

docs/mobile-browsers.md
- Updated `mobile-browsers.md` to include Brave's official F-Droid repository.
- Relevant discussion: https://discuss.privacyguides.net/t/add-f-droid-download-link-to-brave-browser-recommendation/28816
=> update: Mention new Brave F-Droid repository

docs/maps.md
- Add sections under OsmAnd's recommendation card that indicates the analytics within the app and ways to disable them if available.
- This was first brought up by a community member in the PG Matrix, and I have also personally downloaded and tested both the Android and iOS versions for confirmation.
- Reword the introduction to the recommendation page and the blurb for the OsmAnd card to reflect the above changes
=> update: Add sections about OsmAnd's analytics

docs/email.md
I noticed an incorrect wording
You should consider whether the provider which has the features you require ---> You should consider whether the provider has the features you require.
=> style: Change wording in Email Services criteria

docs/browser-extensions.md
-As discussed  in [Privacy Guides forum](https://discuss.privacyguides.net/t/inaccurate-statement-in-the-browser-extensions-section/28090)
-Specify that filter lists are updated every two days, not every major extension release
=> update: Clarify uBO Lite update timeline

docs/frontends.md
- Added watch and search history to the sentence
Conflict of interest: I am one of the maintainers of FreeTube :)
=> update: Clarify locally stored info with FreeTube

docs/about.md, theme/main.html
=> docs: Link to TikTok profile

README.md
- Fix typos in README.md
- Adjust wording in README.md for clarity
=> style: Fixed Typos And Clarified Wording in README
