privacyguides/privacyguides.org

- legacy_pages/providers/vpn.html
We could add a link to IVPN's Privacy Guides. They are very vendor neutral and not written in such a way that seems like it is selling a particular service.
From what I can see, they're a value added feature of their service. They've obviously put time into making sure the information is accurate.
They are also one of our already recommended providers.
> Link to IVPN Privacy Guides

- _includes/legacy/sections/video-frontends.html
The invidio.us instance has been dead for more than a year now, we moved to a new domain almost 1 year ago, in January... yet you never updated the link.
You are still sending thousands of users to a domain we don't own (we just control it) and that have been kept alive - as a redirect - because a ton of people - including you - still link to it because they never update their stuff.
Please, can you at least use what you recommend (because this shows that you obviously don't) or at the very least CHECK that the link aren't dead and/or haven't moved?!
Thank you.
> Invidio.us has been replaced by Invidious.io... a year ago

- legacy_pages/providers/vpn.html
1. Links pointing to pt.io pages changed to root-related
2. Blog links changed to medium.com Privacy Guides version where possible
3. Link to VikingVPN blog post removed (404, provider defunct)
Community disclaimer: I'm part of the IVPN team, but I add suggestions to PrivacyGuides pages in a personal capacity. To avoid conflict of interest I'm not suggesting changes to VPN recommendation sections and will not include links to IVPN related projects.
> Small fixes on VPN page

- _includes/recommendation-card.html
Add optional `privacy-policy` to [recommendation layout](https://github.com/privacyguides/privacyguides.org/blob/main/_layouts/recommendation.html).
Haven't tested it but it should look exactly like `privacy-policy` in legacy [`cardv2.html`](https://github.com/privacyguides/privacyguides.org/blob/main/_includes/legacy/cardv2.html).
> Re-add privacy_policy functionality

- _data/nav/3_software.yml
In the navbar, the icon of `Video Streaming` (under `Software`) is currently the YouTube's logo.
I changed it to a generic video icon.
Additionally, it is a duotone icon that blends well with others.
> Change 'Video Streaming' icon

- legacy_pages/providers/social-networks.html
We're moving away from recommending extensions in general. This extension hasn't been updated for a long time and was never evaluated for privacy or security.
> Remove mastodon-simplified-federation

- _includes/breadcrumbs.html
Since the link goes to the editor and it has a pencil icon next to it, 'Edit on GitHub' seems more appropriate.
> Change 'View on GitHub' to 'Edit on GitHub'

- _data/software/messengers/1_signal.yml
Line 11 changed "reciepient" to "recipient" to fix typo.
> Fixing typo of recipient on line 11

- _includes/legacy/sections/email-providers.html
Startmail domains are now available to non-business customers.
The [previous article](https://web.archive.org/web/20211120045059/https://support.startmail.com/hc/en-us/articles/360006840058) seems to be now deleted.
https://deploy-preview-528--privacyguides.netlify.app/providers/email/#startmail
> Startmail domains for non-business accounts

- _includes/legacy/sections/file-sharing.html
The service no longer exists, as seen at the URL, so warning about its logging is no longer necessary.
> FramaDrop warning removed

- collections/_evergreen/android.html
I don't want to completely remove CalyxOS just yet, but we really cannot recommend it in its current state. The firmware patch level is 4 months out of date on both the stable and beta branch (yes, I am aware that it is fixed on the testing branch), and Chromium browser & webview are completely outdated on all branches. https://github.com/privacyguides/privacyguides.org/pull/548#issuecomment-1018245074. 
I'd like to give them the benefit of the doubt and wait a bit longer to see how things work out, but in its current state, I don't think Calyx is a good recommendation anymore.
> Add a warning for CalyxOS

- collections/_evergreen/android.html
Originally I removed the mention of the beta branch in the warning because someone linked me the post on Calyx's website about Android 12 being in Beta https://calyxos.org/news/2022/01/19/android-12-changelog/
It is not. Apparently, the update servers says otherwise. Here are a few examples:
https://release.calyxinstitute.org/barbet-beta
https://release.calyxinstitute.org/barbet-testing
https://release.calyxinstitute.org/redfin-beta
https://release.calyxinstitute.org/redfin-testing
The beta branch is still on Android 11 despite of what that post says. Only the testing branch is on Android 12. 
If you look at the pixel 6 series:
https://release.calyxinstitute.org/raven-beta
https://release.calyxinstitute.org/oriole-beta
They don't exist on the beta branch right now. Only the testing …
> Reverting commit 78f69ad

- collections/_evergreen/android.md
Adding this to the Android page for now, as it does affect stock Android. When we discuss ChromeOS/ChromeOS Flex, or other Google products, we could consider making a page dedicated to recommendations with the Google Account and linking to that page instead.
> Adding Advanced Protection Program

- _data/software/browsers-mobile/3_firefox_focus.yml
Resolves #655
This change was supposed to be in #650, but was not included in its successor #698.
> Use dark mode trashcan icon in dark mode (Firefox Focus)

- _data/providers/search-engines/1_duckduckgo.yml
Changed the description of DuckDuckGo to indicate that the results are [from Bing](https://help.duckduckgo.com/results/sources/), not its own crawler.
Resolves: #699
> DuckDuckGo Correction

- _data/software/browsers-resources/2_adguard.yml
Resolves: #724 
Adds privacy policy to the AdGuard for iOS card.
I used the [privacy policy for safari browser](https://adguard.com/en/privacy/safari.html) instead of the [general](https://adguard.com/en/privacy.html) one.
> Add AdGuard privacy policy

- _includes/head.html
- feed.json
[JSON Feed](https://www.jsonfeed.org/) is the new, modern standard for feeds.
This PR ties into #25 (and #744).
Changes:
- Add JSON feed
- Add JSON & XML feeds to site head
> JSON feed for blog posts

- _config.yml
- feed.xml
This PR ties into #25 (and #714) and fixes what was discussed in #671.
Currently the site uses the jekyll-feed plugin for Atom feed generation. It, for whatever reason, doesn't account for posts having multiple authors. I copied the jekyll-feed [layout](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml) and modified it to work nicely with multiple authors.
> Fix Atom feed multi-author formatting

- _includes/head.html
Resolves: #573 
Before
```HTML
<meta name="description" content="Android is a secure operating system that has strong [app sandboxing](https://source.android.com/security/app-sandbox), [verified boot](https://source.android.com/security/verifiedboot), and a robust [permission](https://developer.android.com/guide/topics/permissions/overview) control system.
The main privacy concern with most Android devices is that they usually include [Google Play Services](https://developers.google.com/android/guides/overview). This component is proprietary, [closed source](https://en.wikipedia.org/wiki/Proprietary_software), has a privileged role on your phone, and may collect private user information. It is not a part of the [Android Open Source Project](https://source.android.com/) (AOSP) nor is it …
```
> Fix meta description tags

- _includes/legacy/cardv2.html
Fixes the `image-dark` tag in cardv2
> Fix cardv2 dark mode images

- collections/_evergreen/linux-desktop.md
The word "either" seems like a stray word, since there is no
alternative listed within the same sentence.  The alternative of using
a specified sysctl setting in `linux-hardened` is immediately explained
in the following new line/paragraph.
> Remove superflous "either"

- _includes/legacy/sections/vpn.html
- legacy_pages/providers/vpn.html
Someone on Matrix mentioned that currently the page states WireGuard is "experimental" and "not currently recommended for production use." I think these statements aren't entirely accurate anymore; WireGuard has proven itself as is demonstrated by almost all reputable VPN companies ([Mullvad](https://mullvad.net/en/help/why-wireguard/), [IVPN](https://www.ivpn.net/wireguard/), [ProtonVPN](https://protonvpn.com/blog/wireguard/), etc) adopting it as a default and by it being incorporated into the Linux kernel.
- Update WireGuard description for all providers
- Update minimum to qualify criteria to include WireGuard
- Update criteria alert to include WireGuard and add line break before long link
- Include WireGuard support for ProtonVPN
- State for which apps, per provider, WireGuard is the …
> Update WireGuard information on VPN provider page

- _data/operating-systems/android/2_calyxos.yml
- collections/_evergreen/android.md
Closes https://github.com/privacyguides/privacyguides.org/issues/648
I removed the firewall comparison and mentions of the leaks. They have supposedly fixed it, but the lack of documentations (their website still talks about their old firewall) makes it hard to have an accurate comparison. We'll add back the Firewall comparison later.
I also removed mentions of Calyx's OS support for the Xiaomi A2 and Pixel 2.
> Calyx firewall

- collections/_evergreen/linux-desktop.md
- collections/_evergreen/router.md
Correct spelling of Wi-Fi (according to Wikipedia) in Linux Desktop &
Router pages
> Correct spelling of Wi-Fi

- docs/dns.md
Currently, the flowchart in Providers -> DNS Servers is missing a 'Yes' branch from the 'Want Privacy from ISP?' decision box. This corrects it to have a Yes branch going to 'Use a VPN or Tor', as shown in #767
> Include 'Yes' branch in DNS flowchart

- docs/email-clients.md
Resolves: Removes wrong ios app store link for FairEmail#
> Remove wrong ios app store link for FairEmail

- docs/email.md
Changed tutanota.org to tutanota.com because .org domain doesn't work.
> Tutanota domain fix

- README.md
- Regarding removal of `mkdocs` installation, `mkdocs-material` installs it as part of it's dependency.
- Only [Python 3.6 and above](https://github.com/squidfunk/mkdocs-material/blob/f4f9c21d32521db90444986d81ce801e98ac0fbf/setup.py#L67) works with `mkdocs-material`.
> Improve building instructions

- docs/browsers.md
> all browsers on the App Store are essentially Safari under the hood
I didn't like how this sounded as it's not entirely accurate as I've recently learned.\
See https://developer.apple.com/forums/thread/88052 & https://news.ycombinator.com/item?id=15872111
This rewrite is also less scientific, as in it's easier to understand. Most people don't know or care what WKWebView is.
I also removed the Safari download button because it's already built into any supported OS, so I don't really see the point of having it when the homepage and privacy policy are already linked.
> Clarify iOS browser restrictions

- docs/file-sharing.md
Closes: https://github.com/privacytools/privacytools.io/issues/2385
I was browsing through our [old repo](https://github.com/privacytools/privacytools.io/issues/991) and noticed this  PR https://github.com/privacytools/privacytools.io/pull/2386.
Seems it was added [a long time ago](https://github.com/privacytools/privacytools.io/commit/23804e3844c19644f14586b0cc56d8c83eec2519) without much discussion.
We should have a warning for this, or consider removing it. The software is still actively developed.
https://www.reddit.com/r/cryptography/comments/mult11/siec_elliptic_curve_vs_other_better_known_ones/
> Add warning about SEIC curve

- docs/tools.md
In this context it was recommended as a browser extension whereas on the full browser page that is explicitly contradicted.
> We do not recommend installing ToS;DR as a browser extension. The same information is provided on their website.
> Add TOSDR disclaimer on overview page

- docs/android.md
More thoroughly notes what features DivestOS includes.
- https://divestos.org/index.php?page=news
- https://divestos.org/index.php?page=technical_details
Also sadly removes the Bromite WebView option, for some unknown reason it causes the 15.1 branch to not boot.
> Detail the DivestOS hardening

- docs/setup/integrating-metadata-removal.md
- Updated the beginning paragraph. I wasn't a fan of how I worded it before
- Add a "Related" admonition with a link to the main metadata removal page
- Removed the note with more information on ExifTool (because of the above ^ change)
- Removed the note to take note of ExifTool's location since the script doesn't need it anymore
- Added a paragraph stating that people are free to modify the shortcut as they please to fit their desired functionality
- Updated the ImageOptim admonition
- Some other grammar stuff
> Minor updates to the Integrating Metadata Removal article

- docs/metadata-removal-tools.md
This PR corrects the F-Droid link for the metadata removal tool Imagepipe. 
Currently the link forwards to Scrambled Exif F-Droid page.
> Imagepipe F-Droid link correction

- .github/CODEOWNERS
- .github/workflows/deploy.yml
- CHANGELOG.md
- README.md
From discussion #980 
This changes our deployment so that changes are **not** made on every push to `main`. The website is only updated when a release is published on GitHub. Hopefully it's better for people keeping track of changes to the website, it will also show a version number on the website. When we get translations going, having an easily visible version number/release schedule will make it easy to compare translations the main website.
This also adds a CHANGELOG.md file which ideally should be updated in every PR. We can then easily copy new info from that file to the release description when we deploy a new release.
> Add changelog, deploy on tagged releases

- CHANGELOG.md
- mkdocs.yml
Adds a navbar link to the new [organization discussions](https://github.com/orgs/privacyguides/discussions).
By having a prominent link to the discussions I'm thinking it could get more people involved.
> Add link to Discussions in nav bar

- docs/tools.en.md
This adds [annotations](https://squidfunk.github.io/mkdocs-material/reference/annotations/) to the ToS;DR and Qubes entries on `/tools/` rather than the current `*` notes.
> Use annotations for tool notes

- docs/linux-desktop.en.md
Mostly 1 typo and stylization corrections:
* spelling of SD card, according to [Wikipedia](https://en.wikipedia.org/wiki/SD_card)
* use modern stylization of Xfce, according to [Wikipedia](https://en.wikipedia.org/wiki/Xfce)
* Capitalize Vaultwarden, according to its [Wiki](https://github.com/dani-garcia/vaultwarden/wiki)
> Minor fix on Linux page

- docs/tools.en.md
DecSync in tools section is called DecSync while in seperate section its called DecSync CC
Now its called DecSync CC everywhere
> More consistent wording

- docs/vpn.en.md
Is there a specific reason to why we mentioned the WireShark trademark info? It's inconsistent since we do not mention other trademarks.
> Remove WireShark trademark reference

- crowdin.yml
- docs/android.en.md
- docs/android/overview.en.md
- docs/android/security.en.md
- docs/browsers.en.md
- docs/calendar-contacts.en.md
- docs/cloud.en.md
- docs/dns.en.md
- docs/email-clients.en.md
- docs/email.en.md
- docs/encryption.en.md
- docs/linux-desktop.en.md
- docs/metadata-removal-tools.en.md
- docs/multi-factor-authentication.en.md
- docs/notebooks.en.md
- docs/passwords.en.md
- docs/real-time-communication.en.md
- docs/router.en.md
- docs/search-engines.en.md
- docs/security/multi-factor-authentication.en.md
- docs/self-contained-networks.en.md
- docs/setup/integrating-metadata-removal.en.md
- docs/technology/dns.en.md
- docs/tools.en.md
- docs/video-streaming.en.md
- docs/vpn.en.md
- includes/abbreviations.en.md
- mkdocs.yml
This change:
- Adds support for abbreviations: https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
- Makes use of abbreviations more consistently throughout the website
> Use abbreviations across site

- mkdocs.yml
Since @dngray changed some bold text to h5 headers in #1085 (which was the right move) the table of contents sidebar is a bit cluttered (see https://www.privacyguides.org/browsers/ for example). This limits the toc to only go down to h4 so we can keep them without extraneous toc entries.
[old](https://user-images.githubusercontent.com/3637842/164943173-6c296284-c59f-40e6-81cb-bfd762ead7fb.png) vs [new](https://user-images.githubusercontent.com/3637842/164943177-7c7b6be8-7594-4365-88d7-9ef49fc436f5.png)
> Set toc_depth of 4

- docs/browsers.en.md
- docs/cloud.en.md
- docs/dns.en.md
- docs/email-clients.en.md
- docs/encryption.en.md
- docs/metadata-removal-tools.en.md
- docs/multi-factor-authentication.en.md
- docs/notebooks.en.md
- docs/passwords.en.md
- docs/router.en.md
- docs/search-engines.en.md
- docs/setup/integrating-metadata-removal.en.md
- docs/vpn.en.md
We don't want to over-use them, because they should specifically call out important information. We have a number of (especially "notes" and "info") admonitions that could just as easily be plain-text, because their content isn't particularly more important than other content on the page.
> Reduce the number of admonitions across the site

- docs/email.en.md
Moves email cloaking services and self-hosted email solutions higher up on the email providers page (below the email services recommendations).
I think they are better off higher on the page as they're important, especially email cloaking services.
After this gets merged/closed I plan on adding more info to the email cloaking services section; it is quite sparse of information.
> Move email cloaking services and self-hosted email under provider recommendations

- .allowed_signers
SSH commit signing is:
- Supported in Git
- Supported in Gitea, for example: https://code.privacyguides.dev/privacyguides/privacyguides.org/commit/7ed368c3eae2ebf5e9a0368724eda1ebbee29480
- Will be imminently supported in GitHub: https://github.com/github/feedback/discussions/7744#discussioncomment-2603637
In light of this third fact, I am switching my commit signatures to SSH. For now GitHub will display these as Unverified, but this will be fixed once GitHub updates their website.
To locally verify commits made to this repo, run this command (after this PR is merged):
```
git config gpg.ssh.allowedSignersFile .allowed_signers
```
Then you can:
```
$ git show --show-signature                             
commit 7ed368c3eae2ebf5e9a0368724eda1ebbee29480 (HEAD -> pr-ssh-signing, …
```
> Enable SSH Git commit signing

- docs/real-time-communication.en.md
- includes/abbreviations.en.md
I was researching Session so I took the time to update the recommendation with some more polished info.
I replaced the download links with non-direct download links. I think linking to a direct download is a bad practice; visitors should ensure their download comes from the actual site, which is harder to determine with a direct link. I also removed the Android download link since it was a duplicate of the F-Droid link.
> Session messenger update

- README.md
- docs/index.en.md
Since we have Mastodon now, and it's somewhat mainstream as of late, it makes more sense to start promoting this primarily as our social media platform. We'll still keep Twitter in the README and website footer.
> Link to Mastodon instead of Twitter

- docs/search-engines.en.md
As anyone who has tried using Startpage knows, they offer limited access to those using a VPN or Tor, making it difficult to use the service.
The site currently states:
> [Startpage] is a very convenient way to get Google search results without experiencing dark patterns such as difficult captchas or being refused access because you used a VPN or Tor.
I felt this is wildly inaccurate, and so I'm making this PR.
I've also gone ahead and added some information on Startpage's flagship feature: Anonymous View. I detailed this feature to the best of my ability, primarily basing it off of the information provided in the feature's [technical document](https://support.startpage.com/index.php?/Knowledgebase/Article/View/1185/0/the-anonymous-view-proxy---technical-details=undefined). However, I …
> Update Startpage recommendation

- docs/browsers.en.md
"The HTTP protocol" is redundant.
> Fix redundant text in the Firefox card

- docs/technology/dns.en.md
Just spotted a misdirecting markdown link on the "Introduction to DNS" page :)
> Fix VPN link on "Introduction to DNS"

- docs/browsers.en.md
Resolves: #1196 
"it should be safe to use" makes it sound like we're unsure about recommending it. Removed this part so it is shorter and more confident.
> Fix wording on Firefox sync

- docs/browsers.en.md
The configuration guides for the browser section were inconsistent so I fixed it.
> Make the instructions more consistent in the browser section

- docs/browsers.en.md
Detail some of the benefits of Safari Private Browsing, added macOS instructions, and refined the iOS instructions based on [Apple's instructions](https://support.apple.com/en-us/HT203036).
> Detail Safari Private Browsing

- docs/dns.en.md
The "Type" column in the DNS providers table is unnecessary as whether a provider is commercial or not is irrelevant; the only thing that matters in terms of how they'll treat your data is their privacy policy. Also removing a column should help the table feel less squished.
Resolves: #1208
> Remove type column from dns table

- docs/linux-desktop/overview.en.md
- docs/security/multi-factor-authentication.en.md
- docs/stylesheets/extra.css
Resolves the issue where the embeds become visually glitchy when resizing the window. It now maintains a 16:9 aspect ratio
follow up to #1230
> Maintain aspect ratio of YouTube embeds

- docs/tools.en.md
I originally thought the Browser learn more link went missing since it's pushed down so far, so I took that as a sign that the links should probably be added for both the main and subsections.
> Add "learn more" links to subsections

- docs/tools.en.md
It was renamed with #1133
I also reordered the two services in the way they appear on the main page
> Rename "email cloaking" to "email aliasing" on overview page

- docs/browsers.en.md
Recommend to only use UBO in its default configuration.
Resolves: #1237
> Edit ubo to not recommend installing all filter lists

- docs/browsers.en.md
I think adding UBO on Brave is close to useless because it would be redundant with **Shield** feature of the browser.
I'm not sure about my syntax of my sentences though as english isn't my native language.
Please reconsider my grammar, vocabulary and the syntax if you'll agree to merge this.
> Add warning to avoid third-party extensions on Brave

- docs/browsers.en.md
- Embedded Snowflake proxy on page
- Removed redundant "extensions" sections in favor of [one warning](https://github.com/privacyguides/privacyguides.org/pull/1275/files#diff-56f4df316267bf67baec6ca82c6845d785a002e3aa1bb3a1b9044dc80dc0e52eR301).
- Reverts #1269
> Improve Snowflake section and extension warnings

- docs/tools.en.md
I've received a lot of feedback that it is difficult to find information on each tool from the overview page on mobile specifically. Since we write a lot about our recommendations now it makes more sense to link to the cards rather than the third-party websites.
> Link to internal pages from overview

- README.md
I've updated the README images to make use of the new theme context syntax released yesterday (https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/)
*also: https://github.com/privacyguides/.github/pull/4*
> **Note**
> This has two benefits:
> 1. No longer includes `#gh-light/dark-mode-only` in the linked URL
> 2. Should fix the missing image issue on the git mirrors
(this note thing is new too lol, wanted to test it out)
> Improve README images

- docs/video-streaming.en.md
A couple of suggestions from "Certified Google Pixel Enthusiast (and noted light mode enjoyer)" in Matrix
> Also just FYI, for Newpipe we mention that it also allows you to view videos on Framatube: https://www.privacyguides.org/video-streaming/#newpipe
>
> We should change this to Peertube instead. While Framatube is the default instance, you can change the instance in Settings > Content > PeerTube Instances
> Furthermore, since we mention this for FreeTube:
>
> >When using FreeTube, your IP address may still be known to YouTube, Invidious, or SponsorBlock depending on your configuration. Consider using a VPN or Tor if your threat model requires hiding your IP address.
>
> We should also mention it about NewPipe since it does make connections to YouTube, there's no proxying happening …
> Update NewPipe description

- docs/email.en.md
- docs/vpn.en.md
Closes: https://github.com/privacytools/privacytools.io/issues/1437
> Removing Jurisdiction Requirements

- docs/news-aggregators.en.md
- docs/tools.en.md
Feeder seems to be better actively developed by the community, has CI set up, and support JSON feeds.
Now that it has features such as pinning, and folders, I don't see any real reason to use this.
> Remove Handy News Reader

- docs/linux-desktop/hardening.en.md
I don't like polarbears. 
On a serious note though, the without the last sentence, the GRSecurity part sounds weird. As for the LKRG kernel module, the point here is not that it is available on KickSecure, the point here is that if you use Debian you should just add the KickSecure repo and install it since it is fairly easy anyways. Same for Arch and possibly Fedora in the future.
I also updated the mountpoint hardening section since `noexec` on /home and /root breaks a lot of stuff.
> Fixes for the Linux Page

- docs/assets/stylesheets/extra.css
I like everything about `mkdocs-material` except the *Material* part. Experimenting with some changes to make the site a little bit more unique and less google-y. This PR currently changes admonitions, cards, buttons, search.
> Improve Colors and Styles

- README.md
`mkdocs serve` wouldn't work due to a missing rss plugin that was added in c2059a392bb0b3371b7b9aba4efd70d4e5a54713
This PR updates README.md to include that new dependency
> Add rss plugin dependency to README.md

- docs/browsers.en.md
The design of the Snowflake embed doesn't really fit in with the site design and it also takes up unnecessary screen real estate for those who don't make use of it, and so it's probably best to put it behind a collapsable admonition.
> Move snowflake embed into a collapsable admonition

- docs/real-time-communication.en.md
This page used to be fine how it was. We list centralized messengers first, then federated networks, then messengers with anonymous routing. The current page is a mess.
We literally explains the type of network right now below, why are we not following that for our recommendations?
Also, remember that generally, centralized messengers are the easiest to use, because you just sign up and use it. That is followed by the federated messengers, because you have to grasp the concept of the homeservers and what not. We list anonymously routed messengers last because they are generally harder to use.
> Update Real-Time Communication page ordering and categorization

- docs/multi-factor-authentication.en.md
The NitroKey should never be listed before the Yubikey. The reasoning has always been provided since day 1. This PR simply reverts the alphabetical ordering.
I added 1 single sentence in the warning in case it is not clear enough.
> Fix 2FA ordering

- docs/search-engines.en.md
- docs/tools.en.md
DDG > Brave > SearcXNG > Startpage.
The reasoning for this is literally already listed for most of them. DDG supports no JS mode, making it the best of the bunch. Brave has anonymous analytics enabled by default so it's worse than DDG.
The only thing that's not mentioned is that StartPage sometimes block VPN or Tor IPs, so it is not as friendly and therefore is put at the bottom. This PR added that.
> Update Search Engine page

- docs/vpn.en.md
Re-ordering the VPN Providers as discussion on Matrix:
1. Proton: having the most countries, using username + password + 2FA, owns 3 giant DCs and their servers and having their own network. Superior compatibility with Linux. Major deficiency: no permanent killswitch on macOS.
2. IVPN: Has 2FA, has Linux repos. Not so good stuff: not owning or operating any ASN.
3. Mullvad: Own some servers. Need to research if they own their network. Not so good stuff: no 2FA, no Linux repos
We should also look at the level of the audits. Some of these providers have only audited their apps and not full network.
> Update VPN Providers page ordering

- docs/real-time-communication.en.md
- docs/tools.en.md
Signal should be in position 1.
It is simpler to use than Element, and in most cases a substitute from SMS is what people are looking for. It also produces the least amount of metadata.
> Update Real Time Communication page ordering

- docs/email.en.md
- docs/tools.en.md
Proton Mail should be #1.
The reason for this is that they have the bridge, which ensures that email is encrypted zero knowledge before uploaded to Proton Mail's servers.
Mail with Mailbox.org's zero knowledge depends on a sieve filter that will only work if the mail comes in the inbox, or gets saved in Sent.
There is quite a risk of unencrypted drafts being saved.
All options should be placed above Tutanota, as there's no way to send an encrypted email to a Tutanota user unless you are either on Tutanota, or use a "temporary inbox". Their encryption is centralized and depends on you trusting Tutanota's servers.
> Update Email Providers page ordering

- docs/android.en.md
I think CalyxOS should be only used for the OnePlus 8/9 and the FP4 for those who need Google Play Services.
Because if they don't, they should stick with DivestOS.
Moreover DivestOS is more hardened than CalyxOS.
That's why I think DivestOS should be recommended after GrapheneOS.
I also put this sentence :
> We only recommend CalyxOS as a harm reduction measure for the OnePlus 8T, OnePlus 9, and especially the Fairphone 4 if you need microG.
... in the box presentation (idk how you call that) of CalyxOS, bc I think it's important notice.
> Reorder DivestOS and CalyxOS

- docs/basics/email-security.en.md
We could add one, but it was doing nothing as a standalone piece of text.
> Removing email provider security section

- docs/cloud.en.md
- docs/tools.en.md
Resolves: https://github.com/privacyguides/privacyguides.org/discussions/1435
Removed Tahoe-LAFS from the Cloud page, as well as the Tools page
> Remove Tahoe-LAFS

- docs/browsers.en.md
Bromite changed where its always open in incognito option was located. It's currently in a separate section titled "Incognito mode".
The guide was unclear of where to find this option, so this small correction should clear up confusion.
> Update location of Bromite always-incognito option.

- docs/android/overview.en.md
I removed parentheses, I don't know why they are there.
In my sentence, people could understand that they can buy a Google Pixel **AND** installing a AV app.
I'm wondering if we should recommend that people shouldn't use AV on android at all.
> Wording and remove parentheses in Android Overview

- docs/linux-desktop/overview.en.md
I migrated my URL format a while back. While I keep re-directs in place
to avoid broken links, it's better to use the canonical version.
(PS: you might wanna take a look at one of the hundreds of broken-link checkers out there. Many of them can pick up unnecessary re-directs.)
> Chore: remove link redirect

- docs/linux-desktop.en.md
- docs/linux-desktop/overview.en.md
There's a link that point there's nothing. I guess it should point here -> https://wiki.archlinux.org/title/System_maintenance
> Add link arch system maintenance

- docs/email.en.md
SimpleLogin has updated the maximum aliases on the free plan from 15 to 10 for new users([source](https://www.reddit.com/r/Simplelogin/comments/w16kph/in_the_coming_weeks_we_are_going_to_change_the/)).
> Update SimpleLogin free aliases number

- theme/overrides/home.en.html
Adds spacing between buttons on mobile, improving consistency and experience.
before / after
> Improve mobile experience

- docs/vpn.en.md
App Store client makes it sound as it if is for the app store, but it is available in the app store instead.
> Fix sentence App Store client -> on the App Store

- docs/multi-factor-authentication.en.md
Replaced GitHub links for contributing etc. with the new website.
> Add Raivo OTP website links

- docs/android.en.md
We removed Scrambled Exif as a recommendation because of the permissions it requests and replaced it with ExifEraser.
Therefore, it makes sense to consistently reference it across the site.
> Replace mention of Scrambled Exif with ExifEraser in Android page

- docs/file-sharing.en.md
- docs/passwords.en.md
- docs/tools.en.md
Bitwarden Send is a feature of Bitwarden, and while they may have chosen to market it as a separate thing, I think listing Bitwarden twice is confusing to our readers.
If this gets merged, we can then mention Bitwarden Send and other projects that feature file sharing in some capacity (Proton Drive would be an example) somewhere in the File Sharing page.
> Remove Bitwarden Send card and add info under main Bitwarden card

- docs/data-redaction.en.md
This PR has two minor fixes:
- Removes mention of Metapho being closed source. Open source is not a requirement, and we also have a source code button for open source recommendations, so readers know what software is open and what is closed. Mentioning it gives it a negative connotation which is not fair.
- Removes mention of Imagepipe under the PrivacyBlur recommendation that was recently moved from the Android page. Imagepipe is not available on the Play Store, while Pocket Paint is (as well as F-droid, if people want that) and it seems a lot more popular and polished (over a million downloads on Play Store). We also[ removed Imagepipe for requesting unnecessary permissions](https://github.com/privacyguides/privacyguides.org/pull/1471), so it doesn't make sense to recommend it elsewhere …
> Small fixes in Data Redaction Page

- docs/vpn.en.md
This PR:
- Removes mention of F-droid from VPN criteria. If our criteria is that VPN clients should be open-source, that's completely fine. Mentioning F-droid by name, however, when we currently issue a lot of warnings and caveats about it felt off.
- Renames "Hidden Service" to "Onion Service", as that is the correct terminology now.
> Small VPN Criteria cleanup

- docs/real-time-communication.en.md
- docs/real-time-communication/communication-network-types.md
- docs/real-time-communication/signal-configuration-hardening.en.md
- mkdocs.yml
This PR:
- Removes the "Types of Communication Networks" section from the Real-Time Communication page, as it seems to be information that's best suited for the Knowledge Base.
- Creates Real-Time Communication Knowledge base Menu
- Adds Signal Configuration and Hardening page under the Real-Time Communication menu as well
> Add Real-Time Communication Category to Knowledge Base

- docs/android/grapheneos-vs-calyxos.en.md
> Fix typo in "GrapheneOS or CalyxOS?" page

- docs/basics/passwords-overview.en.md
This PR makes it more clear why we advise people not to store passwords and TOTP tokens in the same place, as it seems that it has confused some readers:
https://old.reddit.com/r/PrivacyGuides/comments/xnqhqy/totp_codes_in_password_manager/
> Clarify TOTP tokens in password managers in Introduction to Passwords page

- docs/basics/common-threats.en.md
- docs/cloud.en.md
- docs/productivity.en.md
- docs/real-time-communication.en.md
Removes the repetitive and inconsistent warnings about web e2ee across the site.
> Remove warnings for web e2ee across the site

- docs/android.en.md
- docs/calendar-contacts.en.md
- docs/cloud.en.md
- docs/data-redaction.en.md
- docs/desktop-browsers.en.md
- docs/dns.en.md
- docs/email-clients.en.md
- docs/email.en.md
- docs/encryption.en.md
- docs/file-sharing.en.md
- docs/frontends.en.md
- docs/mobile-browsers.en.md
- docs/multi-factor-authentication.en.md
- docs/news-aggregators.en.md
- docs/notebooks.en.md
- docs/passwords.en.md
- docs/productivity.en.md
- docs/real-time-communication.en.md
- docs/real-time-communication/signal-configuration-hardening.en.md
- docs/tor.en.md
- docs/vpn.en.md
|Download Type|Format|Details|
|---|---|---|
|Google Play Store|`[:simple-googleplay: Google Play]()`||
|App Store|`[:simple-appstore: App Store]()`|iOS, macOS, and iPadOS|
|GitHub, etc.|`[:simple-ICON: NAME]()`|Provided that they have a "Releases" section—with downloads—like GitLab and Codeberg|
|Windows|`[:simple-windows11: Windows]()`|.exe files|
|macOS|`[:simple-apple: macOS]()`|.dmg or .pkg files|
|Linux|`[:simple-linux: Linux]()`|.deb, .rpm, etc. *or* distribution-specific instructions|
|PWAs or Extensions|`[:octicons-globe-16: PWA]()` `[:simple-ICON: NAME]()`|Use the browser name. Order: Firefox, Chrome, Edge, Safari|
|Web|`[:octicons-browser-16: Web]()`|e.g. [Snowflake](https://www.privacyguides.org/tor/#snowflake)|
|FreeBSD|`[:simple-freebsd: FreeBSD]()`|| …
> Standardize download sections

- docs/desktop-browsers.en.md
On latest version of Brave, "Private window with Tor" setting moved from "Extensions" to "Privacy and security" section.
> Update Tor window setting location

- docs/linux-desktop/hardening.en.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/1514
I'm not a fan of encrypted boot, or suggesting it for a number of reasons.
1. It's slow, as decryption happens without acceleration features like AES-NI, SSE, etc
2. Only LUKS1 is supported unless you use a patch/development branch, that means compiling it yourself, this is not likely to be compatible with distribution upgrades
3. It doesn't relate to privacy, private data is not stored in `/boot`
4. It does not provide authentication, ie any form of tamper protection ie if the content of `/boot` is in any way predictable, an attacker can modify the volume to contain whatever they want
5. Better off would be to write a TPM guide that uses [`systemd-cryptenroll`](https://www.freedesktop.org/software/systemd/man/systemd-c …
> Remove mention of encrypted boot

- docs/cloud.en.md
This is something we should have recommended against some time ago:
- https://discuss.privacyguides.net/t/remove-nextcloud-e2e-recommendation/10352/7
- https://github.com/privacyguides/privacyguides.org/discussions/1484
It doesn't look like it's made a whole lot of progress either:
- https://github.com/privacytools/privacytools.io/issues/2054#issuecomment-695860956
- https://github.com/privacytools/privacytools.io/issues/197
> Recommend against Nextcloud E2EE

- docs/desktop-browsers.en.md
Firefox Suggest doesn't send data but [search suggestions](https://support.mozilla.org/en-US/kb/search-suggestions-firefox) does. I went ahead and fixed this.
> Fix search suggestions

- docs/email.en.md
We don't stipulate that providers must support IMAP connectivity, because in some cases that is not a requirement for users, we do believe **all** providers must have export functionality in some way or another so that users can choose to leave at a later date.
We also believe all providers must have a feature to see "advanced information" about the emails such as their headers.
> Criteria updates to email: Require export and headers

- docs/email.en.md
I mainly want to split our email providers between services which are built for OpenPGP message encryption and those which are not. I think that's the main differentiating feature people are looking for here.
> Improve email criteria

- docs/desktop-browsers.en.md
I reworded the description to sound a bit better.
It seems that `AdGuard URL Tracking Protection` and `Actually Legitimate URL Shortener Tool` were removed, https://github.com/privacyguides/privacyguides.org/pull/1238/files and these are pretty harmless. This makes our recommendations compatible with https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-recommended which I think is quite reasonable.
Also came up in https://github.com/privacyguides/privacyguides.org/discussions/1328
> Other uBO lists

- docs/os/linux-overview.en.md
This closes:
- https://github.com/privacyguides/privacyguides.org/discussions/1281
- https://github.com/privacyguides/privacyguides.org/discussions/1280
I think it's important not to duplicate too much of upstream documentation.
Windows and macOS instructions should in their respective pages.
> Mention linux updates

- docs/real-time-communication.en.md
- docs/tools.en.md
Rendered alternative proposal to #1994 from discussion at https://discuss.privacyguides.net/t/im-rtc-perfect-forward-secrecy-requirement/11840/5?u=jonah
Closes #1994
> Downrank messengers without PFS

- docs/email-clients.en.md
Added PGP-encrypted since by default Apple Mail supports S/MIME.
> Clarify PGP on Apple Mail

- docs/assets/img/frontends/libretube-dark.svg
- docs/assets/img/frontends/libretube.svg
- docs/frontends.en.md
- docs/tools.en.md
https://discuss.privacyguides.net/t/libretube-newpipe-alternative/11625
> Add LibreTube

- mkdocs.production.yml
- netlify.toml
```
X-Frame-Options = "DENY"
X-XSS-Protection = "0"
X-Content-Type-Options = "nosniff"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Content-Security-Policy = "default-src 'none'; script-src https://www.privacyguides.org https://api.privacyguides.net 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src data: 'self'; connect-src https://api.github.com https://api.privacyguides.net 'self'"
```
> Configure HTTP Headers

- config/mkdocs.common.yml
- theme/assets/stylesheets/extra.css
- theme/partials/header.html
> Use flag for language selector icon

- theme/partials/path-item.html
- theme/partials/path.html
This adds `BreadcrumbList` metadata to the breadcrumbs on the site since they won't be added upstream: https://github.com/squidfunk/mkdocs-material/issues/5091
https://developers.google.com/search/docs/appearance/structured-data/breadcrumb
test with https://search.google.com/test/rich-results
> Add breadcrumb metadata

- docs/cloud.md
Protonmail has released the source code for their apps on march second. This removes the notice that its closed source.
> Remove notice that the protondrive app is not opensource.

- docs/email.md
- includes/abbreviations.en.txt
> Add abbreviation KYC

- docs/android.md
- docs/basics/email-security.md
- docs/email.md
- docs/multi-factor-authentication.md
- Fix typo of YubiKey, YubiCloud (written as Yubikey, Yubicloud)
> Fix typo of YubiKey, YubiCloud

- Brewfile.preview.netlify
- docs/financial-services.md
- netlify.toml
Closes #2116 
- CoinCards doesn't seem to provide service in the UK just yet: https://coincards.com/uk/
> Remove UK from CoinCards countries

- docs/vpn.md
This PR replaces https://www.ivpn.net/apps-android/ link with direct Play Store and Accrescent download links. Direct Play Store link was chosen for consistency with other entries across the site, and Accrescent was added as IVPN made it onto the store.
> Add Accrescent & Play Store Link For IVPN

- docs/news-aggregators.md
- Removes Twitter from the description of Netnewswire
Closes #2138
> Remove mention of built-in Twitter support for Netnewswire

- docs/email-clients.md
- Adds the Protect Mail Activity setting to Apple Mail
closes #2014
> Add mention of Apple Mail's Protect Mail Activity feature

- docs/passwords.md
- Fixes incorrect link to 1password's privacy policy
> Fix 1password privacy policy link

- .cache/plugin/social/fonts/Bagnard/Bold.woff
- .gitignore
- config/layouts/custom.yml
- config/mkdocs.common.yml
- config/mkdocs.en.yml
- config/mkdocs.es.yml
- config/mkdocs.fr.yml
- config/mkdocs.he.yml
- config/mkdocs.nl.yml
- docs/about/index.md
- Better OpenGraph social card images (#2171)
pages w/ cover image:
pages w/o cover image:
homepage:
<details><summary>current sad design</summary>
</details>
> New social card layout

- docs/vpn.md
- includes/abbreviations.en.txt
- Update description of port forwarding in ProtonVPN to mention how to port forward outside of the windows app
> Fix inaccurate port forwarding information for ProtonVPN

- docs/basics/why-privacy-matters.md
Currently there seems to be some issue with those : indentations when exported from Crowdin
- ![why-privacy-matters-crowdin-issue](https://github.com/privacyguides/privacyguides.org/assets/48640805/4613d1a8-7246-41df-aa8a-ebb67265c3af)
> Fix indentation of Why Privacy Matters article

- docs/tools.md
* Fixed Syncthing link (was #syncthing instead of #syncthing-p2p)
* Fixed Nextcloud link navigating to wrong section (was productivity instead of file sharing)
> Fix incorrect links under File Sharing on tools.md

- config/mkdocs-common.yml
- The italian flag icon was irish. I only noticed it on this page, I do not know if it occurs on others pages.
- [ x] I have disclosed any relevant conflicts of interest in my post.
- [ x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [ x] I am the sole author of this work. 
- [ x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).
> Fix Italian flag icon

- docs/real-time-communication.md
- docs/vpn.md
- includes/abbreviations.en.txt
Normalize on "Forward Secrecy", nearly nowhere uses "perfect" anymore, because it doesn't really add anything to the acronym, and nothing is perfect.
> Normalize on "Forward Secrecy"

- docs/mobile-browsers.md
- Changed System Integrity protection to Page Protection Layer as SIP is macOS only
closes #2195
> Fix inaccurate info about Safari SIP

- docs/news-aggregators.md
- Mention how to get channel ID
> Mention how to get channel ID

- theme/partials/logo.html
> Revert pride month logos

- config/layouts/custom.yml
- config/mkdocs-common.yml
- config/mkdocs.zh-Hant.yml
- includes/strings.en.yml
- netlify.toml
- static/_redirects
- theme/assets/stylesheets/lang-zh-Hant.css
- theme/main.html
- Enable `zh-Hant` language
- Add translation notice to footer for `it` and `zh-Hant`
> Enable Chinese Traditional Translation

- Pipfile.lock
- config/layouts/home.yml
- config/layouts/page.yml
- config/layouts/pride.yml
- config/mkdocs-common.yml
- docs/index.md
- Updates mkdocs-material to latest commit
- Resolves https://github.com/privacyguides/privacyguides.org/pull/2223#issuecomment-1643487953
> Add new custom card layouts

- docs/mobile-browsers.md
- Selecting **Strict** under **Upgrade connections to HTTPS** will now upgrade connections to HTTPS and warn users before loading sites that don't support it.
- Resolves https://discuss.privacyguides.net/t/latest-brave-browser-setting-no-longer-there-update-website/13299
> Change regarding "Upgrade connections to HTTPS" on Brave Android

- docs/calendar.md
Cf. https://discuss.privacyguides.net/t/proton-calendar-free-tier-offer-3-calendar-not-one
- Update Proton Calendar information to reflect the current number of calendars offered to free and paid customers of Proton Calendar, as stated in https://proton.me/support/proton-calendar-guide.
> Update Proton Calendar information

- docs/advanced/dns-overview.md
- docs/basics/email-security.md
- docs/email.md
> Add more information about WKD

- docs/email.md
- Add a short note about addy.io's recent security audit by Securitum. Similar to the current note that is already present for SimpleLogin.
Disclosure: I am the owner of the addy.io service.
> Add note about Securitum security audit to addy.io

- docs/encryption.md
- Changes requested by community https://discuss.privacyguides.net/t/enabling-bitlocker-on-the-windows-11-home-edition/13303/19?u=jonah
> Add more information about Bitlocker

- docs/meta/git-recommendations.md
- Add alternative for SSH signing in git for WSL
This PR is to suggest a WSL method for assigning a SSH git key using the `xclip` command, rather than `pbcopy`.
Saves people time figuring out Ubuntu doesn't have the `pbcopy` package, and is pretty straightforward.
> Improve SSH commit signing instructions

- docs/desktop-browsers.md
Max Protection DOH in Firefox is added to Firefox recommended configuration.
This feature is added to Firefox 118 recently.
More Information:
https://support.mozilla.org/en-US/kb/dns-over-https
-
> Recommend "Max Protection" DNS over HTTPS in Firefox

- docs/desktop-browsers.md
Add a warning mentioning Brave's promo code system.
-
> Add warning about Brave's "referral code" system

- README.md
- Remove the link to i18n folder since it no longer exists.
> Remove i18n link from README.md

- docs/advanced/tor-overview.md
- docs/android.md
- docs/basics/common-threats.md
- docs/basics/vpn-overview.md
- docs/desktop.md
- docs/os/qubes-overview.md
- docs/tor.md
**Discussion:** https://discuss.privacyguides.net/t/clarify-tors-weaknesses-with-respect-to-observability/3676/4
- Recommend connecting to a VPN before connecting to Tor
- Include instructions on configuring a ProxyVM in conjunction with `sys-whonix` on Qubes
- Emphasize that Tor traffic looks different from VPN traffic on local/ISP networks
- Include more information about malicious exit nodes
- Includes most changes from #2267
> Clarify and modernize VPN and Tor advice

- docs/basics/account-creation.md
Closes: https://github.com/privacyguides/privacyguides.org/issues/2207
> Clarify data breach risk with OAuth

- docs/data-redaction.md
- Removed dead link to the GNOME extension for MAT2
closes #2320
> MAT2 Nautilus extension deprecated

- docs/dns.md
-  AdGuard DNS has supported ECS since v0.3.1.
> AdGuard DNS supports ECS as of v0.3.1

- theme/assets/stylesheets/home.css
- Update home page styling to have proper margins with smaller screen-widths, like on mobile
- https://discuss.privacyguides.net/t/homepage-has-no-margins-on-mobile/14554
> Update styling to fix margins on mobile

- config/mkdocs-offline.yml
- config/mkdocs.en.yml
- config/mkdocs.es.yml
- config/mkdocs.fr.yml
- config/mkdocs.he.yml
- config/mkdocs.it.yml
- config/mkdocs.nl.yml
- config/mkdocs.ru.yml
- config/mkdocs.zh-Hant.yml
- docs/device-integrity.md
- docs/email.md
- docs/meta/admonitions.md
- docs/photo-management.md
- potential fix for crowdin issues
> Use HTML for admonitions

- docs/news-aggregators.md
- https://discuss.privacyguides.net/t/change-link-to-nitter-instances-in-news-aggregators-page/16018
> Change link to Nitter instances in News Aggregators page

- docs/desktop.md
- docs/os/linux-overview.md
It seems like both distributions in the current 'immutable distributions' category are moving beyond the immutable branding.
Fedora:
> Thirdly, this nice branding term is also a more accurate way of talking about how rpm-ostree works. Fedora Atomic spins are not actually immutable. There are ways to get around the read-only aspects of the implementation even though it is much harder. The nature of the OS, where updates are only implemented when they successfully build and you can rollback or rebase between core host systems, is better described by atomicity than immutability. Atomic is also how many of the contributors who work on rpm-ostree prefer to talk about it! Rebranding provides an opportunity to change the language surrounding this technology.
Nix:
> NixOS also provides atomic …
> Rebranding 'Immutable Distributions'

- docs/frontends.md
- docs/notebooks.md
- docs/passwords.md
- docs/productivity.md
- Convert 
- "Frontends" page
- "Notebooks" page
- "Password managers" page
- "Productivity tools" page
To HTML admonitions.
And so, the HTML admonitions saga for the recommendations category has ended :tada: 
But we now have to convert all Knowledge Base pages to HTML admonitions 😄
> Convert 4 pages to HTML admonitions

- docs/advanced/payments.md
- docs/advanced/tor-overview.md
- docs/basics/account-creation.md
- docs/basics/common-misconceptions.md
- docs/basics/common-threats.md
- docs/basics/multi-factor-authentication.md
- docs/basics/passwords-overview.md
- docs/basics/vpn-overview.md
- docs/os/android-overview.md
- docs/os/ios-overview.md
- docs/os/macos-overview.md
- docs/os/qubes-overview.md
- Convert ALL knowledge base pages to HTML admonitions
- I'd also like to take this opportunity to correct a typo in the "Common Threats page (Mass Surveillance programs section)" on the word "Technopolice" which was written as follows: "Techno**lo**police".
oof, that was a hell of a ride converting EVERY page of the website to HTML admonitions 😄
> Convert ALL knowledge base pages to HTML admonitions

- docs/desktop-browsers.md
- Update the Recommended Configuration section under Brave to reflect Brave's updated settings for sanitizing and storing cookies, as noted here: https://discuss.privacyguides.net/t/changes-in-brave-cookie-settings-and-new-script-blocking-feature/16590
- Move the Social media blocking section to Shields as it is no longer resides in its own section on the sidebar in brave://settings
(I originally submitted a PR on [Codeberg](https://codeberg.org/privacyguides/privacyguides.org/pulls), but it has returned Internal Server Errors for the past week or so.)
> Update Brave cookies settings and move social media blocking

- docs/frontends.md
- docs/productivity.md
- Redirects to the actual Tor instances links page and not the torproject website.
> Include Tor instances link in frontends.md

- docs/real-time-communication.md
Vector-im is the old one, they moved to element-hq
Update Element organization link.
> Update Element organization link

- docs/about/index.md
- Change how team members are displayed:
I do need @freddy-m @blacklight447 @hook9 to [choose an emoji](https://emojipedia.org/twitter) they want to represent them here though. I read @dngray's mind and selected the emoji I thought he'd pick 😂
> Change team member card layout

- docs/os/macos-overview.md
- modify the application security part for os/macos. Some apps in the Mac app store are not sandboxed. See this [discussion](https://discuss.privacyguides.net/t/til-some-mac-app-store-apps-are-not-sandboxed/17466) for details.
> unsandboxed apps in Mac app store

- docs/cryptocurrency.md
- Add MacOS/linux for Cake Wallet
- You can alternatively change it to `Mobile/Desktop`, but Cake does not support Windows at the time of writing.
I previously worked for Cake Wallet but I no longer do. This edit adds 2 platforms that are supported by the app.
> Minor: add MacOS/Linux for Cake Wallet

- docs/desktop-browsers.md
- Remove Brave's Flatpak footnote as it is now verified/endorsed by Brave themselves: https://flathub.org/apps/com.brave.Browser
[Related forum post](https://discuss.privacyguides.net/t/revisit-footnote-next-to-braves-linux-download-link/17575)
> Remove Brave's Flatpak footnote

- docs/email-aliasing.md
- docs/email.md
- Update aliasing links for recommendation cards for the same purpose as https://github.com/privacyguides/privacyguides.org/pull/2471 
- Make minor grammatical changes
> Update remaining email aliasing links

- docs/vpn.md
Basically this is what I envision on probably every service provider page. I like the brief overview the DNS table has at the beginning of the page, and bringing that here with the VPN services and linking each table header to their respective section seems like a good move. Plus with #2438 we can use the same code here to randomize the table order, which I definitely prefer when it comes to these services.
This will be even nicer once we get around to merging #2451 too.
> Add VPN comparison table

- docs/vpn.md
Proton free VPN has servers in 5 countries, not 8. Also modified the link to point to the severs page and seperated visually the two links.
-
> Fix Proton VPN free server number and links

- config/mkdocs-common.yml
- includes/strings.en.env
- Change query string on CSS/JS so that browser caches are invalidated, I was seeing bugs on current PG site release 👀 
- Adds some strings to environment variable file for translation
- Fixes linting errors
> Asset cache-busting & i18n string additions

- docs/tools.md
- Move Snowflake from Tor Browser section to new Alternative Networks section
- Update Snowflake link on `tools.md`
- Add "Learn more" button under the Alternative Networks section
- Rename first section in `tools.md` to "Tor Browser" to reflect the section's new name on the left sidebar
> Move Snowflake to Alternative Networks on Tools page

- docs/search-engines.md
- Add comparison table for the Search Engines page, following the lead of https://github.com/privacyguides/privacyguides.org/pull/2478
- Make changes enumerated [here](https://github.com/privacyguides/privacyguides.org/pull/2505#issuecomment-2047823097) and [here](https://github.com/privacyguides/privacyguides.org/pull/2505#issuecomment-2048081218)
<del>As marked on GitHub, this is a draft PR as wording and formatting is not set in stone. I'm unsure of what to rearrange, add, or remove, so any feedback is welcome. Here are some questions as a starting point:
- **Logging**: Is it better to list information that is logged in the table, and list what isn't logged in the description under each card; or, as in the [DNS comparison …
> Add search engine comparison table

- .devcontainer/devcontainer.json
- docs/basics/common-misconceptions.md
- docs/basics/common-threats.md
- theme/assets/stylesheets/extra.css
- https://discuss.privacyguides.net/t/add-supply-chain-attacks-to-common-threats-page/17595
Closes: https://github.com/privacyguides/privacyguides.org/issues/2382
> Common Threats: Supply chain attacks

- docs/tor.md
- docs/vpn.md
- Fix the footnote providing links to context for the `IsolatDestAddr` preference in the Orbot recommendation
- Under the "[Additional Notes](https://www.privacyguides.org/en/vpn/#additional-notes)" section of the Proton VPN recommendation, replace external link to the Tor Project with an internal link to the Tor Browser card
> Fix hanging footnote under Orbot card

- docs/vpn.md
- Remove mention of ProtonVPN Linux clients not having 2FA
They have released a new Linux client which supports 2FA using TOTP.
https://protonvpn.com/blog/vpn-linux-app/
> Remove mention of ProtonVPN Linux clients not having 2FA

- docs/news-aggregators.md
- Add GitHub releases link for Feeder in the "Downloads" toggle, as that is a valid download source since the Feeder repo's migration from GitLab to GitHub
- Update link in Feeder card so that it points to GitHub instead of GitLab
- Fix grammar error in the NetNewsWire card
<summary>
4) I …
> Add GitHub releases link for Feeder

- docs/advanced/payments.md
- Remove mention of LocalMonero on the Private Payments page
- Relevant discussion: https://discuss.privacyguides.net/t/localmonero-is-shutting-down-most-anonymous-way-to-buy-and-sell-monero/18207
- Fix internal link to Monero card
<summary> …
> Remove mention of LocalMonero in the Knowledge Base

- docs/email.md
- Update link to the GitHub releases page for Proton Mail's Android app
- Relevant discussion: the first sentence of https://discuss.privacyguides.net/t/proton-mail-android-4-0-has-a-new-repo-still-relies-on-fcm-for-push-notifications/18349
<summary>
4) I agree to the Community Code of …
> Update GitHub releases link for Proton Mail Android

- docs/vpn.md
- As a continuation of #2563, mention that IVPN accepts prepaid cards like Mullvad does
- As part of the previous change, embed link to IVPN's "Voucher cards FAQ" since they do not advertise this payment method on their "[Pricing](https://www.ivpn.net/pricing/)" page like [Mullvad does](https://mullvad.net/en/pricing) on theirs (under "Do you offer any type of discount?")
- Make mention of Mullvad's prepaid cards its own sentence for increased readability
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of …
> Mention that IVPN accepts prepaid cards

- Pipfile.lock
- theme/assets/javascripts/discourse-topics.js
- theme/assets/stylesheets/home.css
- theme/home.html
Our homepage is of course our most trafficked page, but despite this it hasn't really changed at all in years. This would make it a bit more dynamic for new visitors.
Adds two different sections to the page:
<summary>
</details>
> Show forum topics on homepage

- docs/cloud.md
- docs/multi-factor-authentication.md
- docs/photo-management.md
- docs/productivity.md
- Ente
- Update the GitHub links for all Ente recommendations to reflect the code consolidation detailed in their [blog](https://ente.io/blog/open-sourcing-our-server/)
- Modify GitHub releases link for Ente Photos to filter the releases to just the entries for Photos (the same was done for the Ente Auth GitHub releases link in #2458)
- Add link to Ente Auth's documentation
- For consistency, modify Stingle GitHub link in the "Downloads" toggle to point to their Android releases page
- Lowercase the word "passkey" on several pages
Closes #2593 
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, …
> Update Ente GitHub links

- docs/meta/commit-messages.md
- mkdocs.yml
> Commit recommendations meta page

- docs/basics/email-security.md
- docs/multi-factor-authentication.md
- docs/os/qubes-overview.md
- Update the last criterion on the Multi-Factor Authentication page (closes #2608)
- In a similar fashion to #2579, the current wording regarding sync would disqualify Ente Auth, which is not at all ideal, considering the recent fiasco with Raivo. Looking at #2251, it looks like this criterion is a vestige of the now-removed Raivo recommendation. I can't access the [discussions](https://github.com/privacyguides/privacyguides.org/pull/1980#issuecomment-1431294392) that led to the [creation of this criterion](https://github.com/privacyguides/privacyguides.org/pull/1980); hopefully, this update keeps the spirit of the original criterion intact.
- Update links for Qubes ProxyVM guides as some of these docs have been migrated to the Qubes …
> fix: Update last criterion on MFA tools page

- docs/passwords.md
- docs/security-keys.md
- Proton Pass
- Remove the last section of the description
- The Proton Mail card already mentions that the service is based in Switzerland (which is visible when hovering over the internal link), and the other pieces of information are, in my opinion, not useful for readers.
- Bold the first instance of "Proton Pass" in the description for consistent styling
- 1Password
- Remove the last paragraph below the 1Password card comparing 1Password to Bitwarden, and integrate the parts highlighting 1Password's features into the first paragraph
- Reasoning for this is similar to what I wrote for the third bullet point in #2504
- Unbold "1Password" in the first sentence of the text below the card for consistent styling
- Change the icons for Proton Pass's and …
> fix: Update Password Managers page

- docs/desktop-browsers.md
- https://discuss.privacyguides.net/t/suggest-disabling-privacy-preserving-ad-measurement-on-firefox/19372/9
<summary>
</details>
> update: Add information about Firefox's "privacy-preserving" ad measurement

- docs/desktop-browsers.md
- docs/mobile-browsers.md
- Mobile Browsers
- Safari
- Remove the URL parameters in the "privacy features" link that lock it to a specific iOS version; the current link is locked to iOS 15, which is not the current iOS version
- Replace the current link for the Documentation button as it points to the docs for Safari on macOS. The replacement link directs readers to the docs for Safari on iOS instead.
- Mention that Private Relay is available only for those who have a paid iCloud+ subscription
- Remove the last sentence of the introduction to this page that advises readers to be judicious about installing extensions, as it is made redundant by the intro to the Browser Extensions page
- Desktop Browsers
- Move the section about PPA to the appropriate section that corresponds with its …
> fix: Replace links to documentation in Safari card

- docs/mobile-browsers.md
- Updated recommended Brave configuration
- ~~Warning about Brave's Google Play Services dependency~~ https://github.com/privacyguides/privacyguides.org/pull/2561#discussion_r1587038135
<summary>
</details>
> Updated recommended Brave configuration

- docs/desktop-browsers.md
Brave switched to just a toggle regarding fingerprinting a while ago, as outlined here: https://brave.com/privacy-updates/28-sunsetting-strict-fingerprinting-mode/
Also being discussed here: https://discuss.privacyguides.net/t/brave-removes-strict-fingerprinting-protection/16302
- Update Brave Fingerprint settings to reflect current options
<summary>
3) I …
> Update Brave Fingerprint settings

- docs/desktop-browsers.md
- Remove [obsolete](https://github.com/brave/brave-browser/issues/32316) warning about PKG on macOS
- ~~Remove anti-fingerprinting mode which [no longer exists](https://brave.com/privacy-updates/28-sunsetting-strict-fingerprinting-mode/)~~
Conflict of interest statement: I work for Brave Software.
<summary>
3) I have disclosed any relevant conflicts of …
> Update obsolete Brave info (pkg on macOS)

- docs/frontends.md
- Replace currently broken YouTube guide link in the Yattee card with a link to an archived version of the guide (fixes #2650)
- Add Oxford commas where appropriate, which are considered [mandatory by APA Style guidelines](https://en.wikipedia.org/wiki/Serial_comma)
<summary>
4) I agree to …
> fix: Replace broken Yattee YouTube guide link

- docs/os/android-overview.md
- Add an introduction to the Security Protections section of the Android Overview page
- The reason for this addition is that the instant preview for the second button on the Mobile Phones page is not very useful currently (see the screenshot below).
- Apply bolding to the subsections of the Security Protections section
- This is already done for subsections of the ["What is "encrypted DNS section?"](https://www.privacyguides.org/en/advanced/dns-overview/#what-is-encrypted-dns).
- Add internal link to Google Pixel card
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the …
> fix: Make minor improvements to the Android Overview

- docs/meta/uploading-images.md
- "Uploading Images" meta page
- Add recommendation for WebP optimization (closes #2660)
- The recommendation here is derived from the [second example](https://developers.google.com/speed/webp/docs/cwebp#examples) provided by the `cwebp` documentation, with the addition of the [`-m int`](https://developers.google.com/speed/webp/docs/cwebp#options) option, which seems to achieve something similar to what the `-o` option for OptiPNG does. (Toggle the table below for a comparison between original JPEG sizes and WebP sizes using the images from #2661 as examples.)
- Add Unsplash recommendation for cover images
- The reasons for this addition were this GitHub [comment](https://github.com/privacyguides/privacyguides.org/pull/2409#issuecomment-1995075794) by Jonah …
> docs: Add recommendation for WebP optimization

- docs/about/donate.md
- docs/os/index.md
- docs/os/windows/index.md
- includes/abbreviations.en.txt
> fix: Improvements on Windows overview

- docs/os/index.md
- Update the internal link to the Android Distributions page on the Operating Systems index page
- Add line break between "Recommended Android Distros" and "The articles marked with [...]" since, on the live site, the latter is on the same line as the former, which is not the best formatting in my opinion
<summary>
3) I have disclosed any relevant …
> fix: Update internal link for Android Distros on OS Index

- mkdocs.yml
- Move the recently published Hardware Guide to the Knowledge Base
- I'm not sure what happened to the commit mentioned [here](https://github.com/privacyguides/privacyguides.org/pull/2268#pullrequestreview-2190058447); regardless, the entry currently in `mkdocs.yml` is not consistent with the rest in the "Recommendations" section. In my opinion, this page being in the KB makes a lot of sense since it doesn't offer tool recommendations in the same way that other pages (like any of the recently split Android pages) do.
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the …
> fix: Move Hardware Guide to Knowledge Base

- docs/about.md
- docs/about/notices.md
- docs/file-sharing.md
- docs/index.md
- Fix the path of the About page on the homepage, which was changed in #2683 but not updated in #2680
- Fix broken Nextcloud logo in file sharing
- Fix absolute link warnings on build
<summary>
</details>
> fix: Resolve build warnings

- docs/meta/commit-messages.md
- Use `style:` in commit messages to denote formatting/grammar/typo-correction changes to the site
Previously we've been marking these either as `fix:` (e.g. https://github.com/privacyguides/privacyguides.org/pull/2681) or `refactor:` (e.g. https://github.com/privacyguides/privacyguides.org/pull/2662). This should eliminate that ambiguity.
<summary>
3) I …
> docs: Use style commit type for minor grammar/typo fixes

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- enables [strict](https://www.mkdocs.org/user-guide/configuration/#strict) mkdocs builds for PR previews, this means PRs will fail to build entirely if there are broken internal links or other warnings, so we catch things like #2684 immediately
<summary>
4) I agree to the Community Code …
> ci: Use strict mkdocs builds on PR previews

- docs/desktop.md
- docs/os/linux-overview.md
- Remove mentions of transactional updates from the Desktop/PC recommendation page and the Linux Overview page
- Relevant discussion: the first part of https://discuss.privacyguides.net/t/about-the-opensuse-tumbleweed-recommendation/18364
- Transactional updates are not officially supported on traditional (non-atomic) distributions like Tumbleweed, as this developer unambiguously states in this [openSUSE bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1221742#c27):
> While transactional-update currently works with a read-write root filesystem, it is really not supported. And if we need to break it for new features, we will break it.
Using transactional-uodate [sic] on a read-write filesystem can lead to data lossage.
- Desktop/PC page
- Replace docs …
> update: Remove mentions of transactional updates and X11 utilities

- docs/basics/multi-factor-authentication.md
- docs/os/linux-overview.md
- remove broken invidious embeds and replace with YouTube links
One of the videos doesn’t even seem to be available anymore. I felt the best way to simplify and prevent future breakage is to just link to the original YouTube video instead of embedding it.
Closes #2564 
<summary>
4) I agree …
> fix: Remove broken invidious embeds

- docs/email-clients.md
- Add iOS download link for Canary Mail, as suggested in https://discuss.privacyguides.net/t/canary-mail-app-store-link-is-only-for-macos/19727
<summary>
</details>
> update: Add Canary Mail iOS download link

- docs/alternative-networks.md
- docs/android/distributions.md
- docs/android/general-apps.md
- docs/browser-extensions.md
- docs/calendar.md
- docs/cloud.md
- docs/cryptocurrency.md
- docs/desktop-browsers.md
- docs/device-integrity.md
- docs/dns.md
- docs/document-collaboration.md
- docs/email-aliasing.md
- docs/encryption.md
- docs/file-sharing.md
- docs/language-tools.md
- docs/mobile-browsers.md
- docs/mobile-phones.md
- docs/multi-factor-authentication.md
- docs/notebooks.md
- docs/passwords.md
- docs/photo-management.md
- docs/real-time-communication.md
- docs/security-keys.md
- docs/tools.md
- docs/tor.md
- docs/vpn.md
- Add threat model labels
- This PR is a continuation of @kimg45's work in #2605.
- Relevant discussion: https://discuss.privacyguides.net/t/implement-threat-model-labels/18659
- I will also implement the improvements I suggested [here](https://github.com/privacyguides/privacyguides.org/pull/2605#pullrequestreview-2199969952), which include
- Instant previews of threat explanations upon hovering over labels
- Explanatory sentences for tools that protect against additional/different threats than other tools on a page
- A signpost on the Recommended Tools page that indicates that this feature is something we're experimenting with
Closes #2605
<details>
<summary>All done!</summary>
- ? dnscrypt-proxy
- ? Send, OnionShare, and Syncthing
- ? Secure Camera
- ? …
> feat!: Add threat model labels (continues #2605)

- README.md
- Fix and update the broken link to the About page of the site in the Readme for this repository (thank you to the person who pointed this out on the PG Matrix)
<summary>
</details>
> style: Fix link to About section in Readme

- docs/about/services.md
- docs/android/distributions.md
- docs/meta/writing-style.md
- Online Services docs page
- Remove mention of the Invidious instance hosted by Privacy Guides, as the purpose of the instance no longer applies since #2585 was merged
- Add periods in two availability sections so that they read more naturally
- Slightly reword for clarity the statement about the audience of Privacy Guides on the Writing Style page
- Add captions for threat model labels on the Custom Android Distros page that I missed in #2689
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to …
> docs: Remove mention of hosted Invidious instance and clean up other pages

- docs/passwords.md
- Recommend switching to Argon2id when using Bitwarden
- Relevant threads: [[1]](https://discuss.privacyguides.net/t/bitwarden-new-argon2id-kdf/11826) [[2]](https://discuss.privacyguides.net/t/suggest-changing-kdf-in-the-bitwarden-recommendation/11854)
<summary>
4) I agree to the Community …
> update: Recommend Argon2id when using Bitwarden

- mkdocs.yml
- Removes https://www.privacyguides.org/en/about/privacytools/ from navigation, i.e. it will only be accessible by direct link
- This page is no longer relevant to any current conversations, and just discusses an old/defunct website. It may be useful to reference directly in the future, but nobody is seeking it out anymore.
- I also just want to reduce the amount of "meta-commentary" we do in general (see also: https://github.com/privacyguides/privacyguides.org/pull/2728#discussion_r1728352403) and let the work speak for itself.
<summary>
2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license …
> docs: Hide PrivacyTools FAQ from navigation

- docs/email-clients.md
- Add condition for blocking cookies on Thunderbird, as it may prevent people from logging in to Gmail if it's enabled beforehand
- Relevant discussion: https://discuss.privacyguides.net/t/set-accept-cookies-from-sites-and-set-accept-third-party-cookies-to-never-in-mozilla-thunderbird/20411/10
- As well as Microsoft365 via SSO according to this reply: https://discuss.privacyguides.net/t/set-accept-cookies-from-sites-and-set-accept-third-party-cookies-to-never-in-mozilla-thunderbird/20411/17
> update: Note that blocking cookies on Thunderbird may affect email logins

- docs/calendar.md
- docs/cloud.md
- docs/email.md
- Replace the privacy policies links for Proton Drive, Mail, and Calendar with links to product-specific privacy policies
- It looks like Proton recently added detailed privacy policies for each of their products. The recommendation cards for Proton VPN and Proton Pass already have these. All of them link back to the general Proton privacy policy.
- Add threat model label to Email Services page
- Standardize syntax for [primary buttons](https://squidfunk.github.io/mkdocs-material/reference/buttons/#adding-primary-buttons)
- Make some minor wording changes
> update: Replace Proton privacy policy links with more specific ones

- docs/email-clients.md
- docs/encryption.md
- Mention that GPG Suite does not yet have a stable release for macOS Sonoma (still in [beta](https://gpgtools.com/sonoma), with the last blog post update about it published in Dec 2023), which directly affects the Apple Mail (macOS) recommendation
- Relevant discussion: https://discuss.privacyguides.net/t/apple-mail-no-longer-meets-minimum-criteria/14950
- This note is intentionally conservative because I'm not sure if there should be an actionable suggestion for this. Would it make sense to advise people on macOS Sonoma to use Thunderbird instead?
- Add the same mention to the GPG Suite listing on the Encryption Software page
> update: Note beta status of GPG Suite on macOS Sonoma

- docs/android/distributions.md
- Correct the advice in the GrapheneOS recommendation about hiding OS info from local network or ISP
- Relevant discussion: https://discuss.privacyguides.net/t/android-connectivity-checks-occur-outside-vpn-tunnels/20441
> update: Correct advice to hide OS info from network on GrapheneOS

- docs/frontends.md
- Piped can no longer play age restricted YouTube videos it seems so I removed the part
> fix: Remove Piped Being Able to Play Age Restricted Videos

- docs/real-time-communication.md
- The current description of Molly-FOSS is incorrect. Molly-FOSS still has working push notifications, just using Websockets rather than Google Play. 
- Added some more detail on Molly-UP. There's also the option of using a public Mollysocket instance, so you don't _have_ to self-host. However the only one I'm aware of is Adminforge.de. I added a link to a step-by-step tutorial, which is in German but it's the only easy-to-follow tutorial I know for a migration from Signal to Molly-UP. Feel free to remove it again if you only want English-language links.
> update: Include more details about FOSS Molly distributions

- docs/browser-extensions.md
- Remove the AMO download link from the uBlock Origin Lite card
- Relevant discussion: https://discuss.privacyguides.net/t/ublock-origin-lite-maker-ends-firefox-store-support/21204
- The above thread links to a third-party article, so here's a direct link to the relevant GitHub issue: https://github.com/uBlockOrigin/uBOL-home/issues/197#issuecomment-2377395301
> update: Remove AMO link from uBOL card

- docs/file-sharing.md
- Remove defunct Google Play Store link in the Downloads section of the Syncthing card
- Relevant discussion: https://discuss.privacyguides.net/t/syncthing-for-android-discontinued/21644/9
> update: Remove Play Store link for Syncthing

- docs/android/general-apps.md
- docs/os/android-overview.md
- Add section in Android Overview page which documents the Private Space feature introduced in Android 15
- Relevant discussion: https://discuss.privacyguides.net/t/remove-shelter/21658/6
- Mention in the beginning of the Shelter listing that using a private space is generally preferred
- Move the statement about recommending Shelter over alternative device controller apps to the space below the warning admonition, as it is not a warning itself
- Update name of setting for managing multiple user profiles
> update: Document Android Private Space and preference for it over Shelter

- docs/desktop-browsers.md
- docs/mobile-browsers.md
- Remove recommendation to disable IPFS functionality in Brave's desktop and mobile apps
- Relevant discussion: https://discuss.privacyguides.net/t/brave-ipfs-gateway-not-in-brave-browser/20895
- Use [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) to cleanly separate settings for the Android and iOS versions of Brave
- This makes sure that the discerning reader using iOS isn't glossing over settings that do not apply to the version of Brave on their device.
- Correct the annotations which describe the Block Scripts setting, as it _does not_ function similarly to uBO's advanced blocking modes based on personal testing
- Relevant discussion: https://discuss.privacyguides.net/t/addition-to-recommended-brave-configuration …
> update: Remove Brave's IPFS mentions and add separate iOS configs

- docs/real-time-communication.md
- Under the Element listing, update the description of how Element handles group calls and its implication on E2EE
- Relevant discussion: https://discuss.privacyguides.net/t/we-have-lift-off-element-x-call-and-server-suite-are-ready/21093
- Note that the changes in this PR are conservative. I entertained the possibility of replacing the current GitHub download link with the one for Element X since it benefits from the integration with Element Call (unlike the legacy app), but some members of the community (such as those in the above thread) reported issues with the app.
> update: Description of group calls for Element

- docs/android/general-apps.md
- docs/data-redaction.md
- docs/desktop.md
- docs/financial-services.md
- docs/language-tools.md
- docs/office-suites.md
- docs/pastebins.md
- docs/router.md
- docs/search-engines.md
- docs/tools.md
This PR is a continuation of #2689.
- Add threat model labels for remaining pages
- Remove admonition in `tools.md` which describes the above feature as an experimental one
- Relevant discussion: https://discuss.privacyguides.net/t/tools-page-improvements/20917
- On the desktop Linux distributions page, add brief footnote about reproducibility and its usefulness against supply chain attacks
> feat: Add remaining threat model labels

- docs/os/macos-overview.md
- remove information about previous versions of macOS
- added link about their promise to implement a mechanism to disable OCSP checks
- removed unsourced claim that the majority of privacy concerns are over iCloud
- add info about Standard Data Protection
- add info about how to check if an app is sandboxed
- add info about the Hardened Runtime
- add info about notarization
- updated for macOS Sequoia
Full disclosure: I copied parts of this from https://github.com/drduh/macOS-Security-and-Privacy-Guide?tab=readme-ov-file#app-sandbox however I wrote these parts so I'm only plagiarizing myself. The commands are from official Apple documentation which I link to so in the interest of having the most accurate info I haven't edited the commands at all
<summary> …
> update: macOS Section

- README.md
- replaced open collective badge with github sponsors on the README
closes #2743
> docs: Replace OpenCollective with Github Sponsors

- docs/about.md
- docs/about/contributors.md
- docs/about/jobs/journalist.md
- docs/basics/account-creation.md
- docs/data-broker-removals.md
- docs/real-time-communication.md
- docs/tools.md
- docs/tor.md
- 'identity' to 'identify' in 'Phone Number' section
> style: typo in 'Create Internet Accounts Privately' guide

- docs/browser-extensions.md
- docs/mobile-browsers.md
- docs/search-engines.md
- docs/tools.md
- theme/assets/img/browsers/cromite.svg
- add Cromite back. Logo (svg) is my own reproduction of the official logo (which is in png).
---
Criteria:
> Must support automatic updates.
yes
> Must receive engine updates in 0-1 days from upstream release.
0-1 days is a bit too strict for a one-person project. [DivestOS claims it's "within a week,"](https://divestos.org/pages/browsers#chromium-based) my personal observation is usually 1 day, occasionally up to 3. Maybe we can ask the maintainer for this
> Any changes required to make the browser more privacy-respecting should not negatively impact user experience.
doesn't appear to
> Android browsers must use the Chromium engine.
yes
> update!: Add Cromite to Mobile Browsers

- docs/meta/uploading-images.md
- Removed the size recommendation for company logos on the Uploading Images page since they'll just be resized anyway, better to have the original version (after optimization)
> docs: Update size requirements for company logos

- docs/passwords.md
* Removes information that states Proton Pass cannot have a password different from the rest of your Proton account.
This PR removes text from the Proton Pass entry that states a separate password cannot be set for Proton Pass. 
Proton added an "Extra password" option to Proton Pass sometime around July 2024:
https://proton.me/blog/pass-secure-link-sharing
> [...]in response to feedback from the community, we’re also launching an Extra Password feature alongside Secure Links. This optional feature lets you create a second password to access credentials stored in Pass for greater compartmentalization and peace of mind. Extra Password is available to the entire Proton Pass community, including those with Free plans.
Screenshot:
Thanks!
> update: Remove outdated master password info from Proton Pass entry

- .github/workflows/publish-pr.yml
- README.md
- blog/.authors.yml
- blog/author/jonah.md
- mkdocs.blog.yml
- mkdocs.yml
<a href="https://bsky.app/profile/privacyguides.org">
> docs: Link to our Bluesky profile

- docs/data-broker-removals.md
- Removes PeekYou and PublicDataUSA from the unsupported site list
Both of these sites are now listed on EasyOptOut's supported sites list: https://www.easyoptouts.com/sites
> update: List of EasyOptOuts unsupported sites

- docs/mobile-browsers.md
- In iOS 18.2, Safari added an HTTPS only mode
> update: Add HTTPS Only mode for Safari

- docs/real-time-communication.md
https://github.com/mollyim/mollyim-android/releases/tag/v7.26.1-1
Molly and Molly-FOSS now support UnifiedPush; Molly-UP is now deprecated and shows a banner telling users to migrate to another Molly app.
> update: Remove Molly-UP mention and update Molly's UnifiedPush support

- docs/os/ios-overview.md
- added info about the new [Clean Up](https://support.apple.com/en-us/121429) feature in iOS that can automatically blur faces and redact information
> update: Add info about the new clean up feature in ios

- docs/vpn.md
-remove part of the text explaining that their Linux client doesn’t support wireguard
Closes #2872
> update: ProtonVPN WireGuard support on Linux client

- docs/financial-services.md
- removed info about privacy.com's discontinued "discreet merchant" feature https://support.privacy.com/hc/en-us/articles/360039145794-Discreet-Merchants
Relevant discussion: https://discuss.privacyguides.net/t/outdated-feature-listed-for-privacy-com-discreet-merchants-discontinued/25294
> update: Replace "discreet merchant" feature with "private spend mode" for privacy.com

- docs/language-tools.md
Fixes #2908 
I believe we got this wrong because LanguageTool's privacy policy states this:
>  When you use our Apps and Extensions, **we collect the following information**:
> 
>  -   Date and time of your usage
>   -  Length of the text
>    - Language of the input text (**but not the text itself**) 
> - [...]
However, they appear to be implying "collect _and store_" when they say the word "collect," because I see no indication that any of LanguageTool's capabilities are possible without at least sending the text to their servers. Their Firefox extension description is more clear about this:
> By default, this extension will check your text by sending it to [languagetool.org](https://prod.outgoing.prod.webservices.mozgcp.net/v1/2784e8753205334dfb8b51e670a33f6c9d5820821f44f3d062f81eb2fd45 …
> update: Correct LanguageTool's data processing note

- docs/mobile-browsers.md
- Brave (mobile)
- Include suggestion to disable V8, which was recently added to the Android version (closes #2900)
- Include suggestion to enable [Auto Shred](https://brave.com/privacy-updates/30-shred-button/) on the iOS version, which functions in a similar way as Forgetful Browsing on desktop and Android does.
> update: New features in Brave Browser Android and iOS

- docs/email.md
- docs/vpn.md
- DNT is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack) so I removed it from the requirements
Relevant discussion: https://discuss.privacyguides.net/t/remove-references-to-dnt-since-it-s-deprecated/25088
> update: Remove references to deprecated DNT

- .mailmap
Team members should use their canonical email addresses rather than noreply.github addresses now that we have a new email setup.
This way we can get accurate statistics when running `git shortlog -nse --group=author --group=trailer:co-authored-by --no-merges` and `git shortlog -nse --group=trailer:signed-off-by`
only spam for the brand new @privacyguides.org accounts of course, the other emails in this file are already public in the git log :P
> docs: Add team members to .mailmap

- blog/posts/privacy-means-safety.md
The previous version wrongly described the arrest of a French climate activist happening in 2012, when these events actually happened in 2021. This was a typo inadvertently inverting the numbers.
> update(blog): Correction of a typo in a date

- docs/photo-management.md
Ente Photos has doubled the limit of their free tier from 5 GB to 10 GB: https://ente.io/#pricing
> update: Change Ente Photos free plan to 10 GB

- blog/posts/signal-configuration-and-hardening.md
- Add built-in censorship circumvention option in Signal beside proxy to bypass internet blocking
Reference:
https://signal.org/blog/doodles-stickers-censorship/
> update(blog): Note Signal censorship circumvention settings

- docs/basics/account-creation.md
- docs/basics/email-security.md
- docs/email-aliasing.md
- docs/email-clients.md
- docs/email.md
- docs/os/android-overview.md
- includes/abbreviations.en.txt
- Email Security page
- Replace link to Wikipedia article about GnuPG with internal link to GnuPG listing
- Make several grammar and wording changes
- Email Aliasing page
- Reorganize the introduction of the page so that the length of the content does not feel overwhelming
- Add two new headers to better organize information
- Reshuffle some sentences in each of the descriptions for Addy.io and SimpleLogin for improved flow of ideas
- Clean up Chrome extension links
- Email Services page
- Update an internal link in the introduction so that it points to one of the new sections of the Email Aliasing page
- Reshuffle some sentences throughout the tool descriptions on the page for better organization
- Highlight private payment methods for each provider …
> style: Reorganize and tweak email-related pages

- .vscode/ltex.dictionary.en-US.txt
- docs/desktop.md
- docs/tools.md
Fedora's website now lists KDE Plasma alongside Workstation under their official Editions. I see no reason to treat this differently than Fedora Atomic Desktops, so this brings both recommendations more in line with each other.
https://discuss.privacyguides.net/t/fedora-kde-is-now-on-the-samel-level-as-fedora-gnome/26706
> update: Recommend both Fedora desktops equally

- docs/real-time-communication.md
- Signal
- Move the link to the Signal hardening guide up so that it's positioned right after the username configuration steps
- This is motivated by the suggestion in FORUM-17828. While moving the settings for call relaying to the main listing may make the description too long, I think foregrounding the link to the guide may be a good compromise. The description also flows better with this change to the order, in my opinion.
- Split the large paragraph in the description under the card into two parts
- The first part outlines what's end-to-end encrypted in Signal; the second outlines other notable privacy features in Signal.
- Molly
- Reformat and restructure part about UnifiedPush and MollySocket into section with a footnote for enhanced readability …
> style: Foreground Signal hardening guide and adjust sections for readability

- docs/calendar.md
- Update the Google Play and App Store download links for Tuta Calendar since the current ones are for Tuta's mail client
- Add GitHub releases link for the Tuta Calendar's Android app
- Make minor style changes
Closes #3057
> update: Download links for Tuta Calendar mobile apps

- docs/mobile-browsers.md
- Update name of V8 setting (for disabling some parts of JIT) on the Android version of Brave
- Relevant discussion: https://discuss.privacyguides.net/t/different-name-for-braves-v8-engine-setting-on-android/29036
> style: Name of V8 setting on Android version of Brave

- docs/desktop-browsers.md
- docs/search-engines.md
- docs/tools.md
- Mullvad Leta
- Relevant discussion: https://discuss.privacyguides.net/t/mullvad-leta/27926
- Add Mullvad Leta to the Search Engines page
- Add Leta to `tools.md`
- Replace external link to Leta homepage with internal link to Leta recommendation card
- Remove line about Brave Search being optimized against Google Search since [Google fallback mixing](https://search.brave.com/help/google-fallback) is disabled by default and only available on Brave Browser
- Make minor style changes
> update!: Add Mullvad Leta to Search Engines page

- includes/strings.en.env
Changed the env var to use double quotes around the value and single quotes in the HTML attributes to avoid issues caused by words containing apostrophes within the text.
> Replace single quote env var with double quote

- docs/os/linux-overview.md
- removed the outdated Fedora blog post
- added instructions on what to do to randomize per-connection for NetworkManager
closes #3027
> update: Remove outdated MAC randomization article for Linux

- .devcontainer/devcontainer.json
- mkdocs.blog.yml
- mkdocs.yml
- theme/assets/stylesheets/extra.css
- theme/main.html
We can pull data from Ghost to display temporary announcements sitewide if we'd like, e.g.:
> feat: Add sitewide announcements bar

- docs/basics/multi-factor-authentication.md
- docs/security-keys.md
- Remove stray `</div>` that wasn't removed in https://github.com/privacyguides/privacyguides.org/pull/3089 which has altered the page formatting (see screenshot below)
- Replace information about available YubiKey OTP slots with link to YubiKey's documentation about it which they keep up-to-date
- For example, firmware version 5.7+ can hold up to 64 TOTP credentials compared to the 32 for older firmware versions.
- Switch current link to Nitrokey comparison table to a link with highlight in lieu of a proper, direct hyperlink to the table
- Replace specific information about Nitrokey's features (i.e., password management) with a link to Nitrokey's documentation
- Embed external link to Wikipedia page for U2F in MFA Knowledge Base page, and remove the …
> style: Fix formatting of Security Keys page and rewrite sections

- blog/posts/age-verification-wants-your-face.md
- blog/posts/cryptpad-review.md
- blog/posts/encryption-is-not-a-crime.md
- blog/posts/importance-of-privacy-for-the-queer-community.md
- blog/posts/in-praise-of-tor.md
- blog/posts/keepassium-review.md
- blog/posts/sam-altman-wants-your-eyeball.md
- blog/posts/selling-surveillance-as-convenience.md
- blog/posts/the-future-of-privacy.md
- blog/posts/the-privacy-of-others.md
- blog/posts/your-online-life-is-irl.md
Shorten meta descriptions for articles with descriptions longer than 300 characters* 
Changes include the following articles:
- age-verification-wants-your-face.md
- cryptpad-review.md
- encryption-is-not-a-crime.md
- importance-of-privacy-for-the-queer-community.md
- in-praise-of-tor.md
- keepassium-review.md
- sam-altman-wants-your-eyeball.md (*added to improve)
- selling-surveillance-as-convenience.md
- the-future-of-privacy.md
- the-privacy-of-others.md
- your-online-life-is-irl.md
> fix(blog): Shorten meta descriptions under 300 characters
